### ISSUE TITLE
Problem running tests for ikos

### ISSUE THREAD

**Issue by hiraditya** [NASA-SW-VnV/ikos#1]
I was trying to run regression testsuite for ikos but all of them failed. Probably because some configurations are missing. I'm unable to find what is the right configuration/environment variable setting before running the tests.

my build configs are as follows:

SRC=~/work/ikos
BUILD=$SRC/build
cd $BUILD

export PATH=/usr/local/opt/llvm@4/bin:$PATH
cmake -GNinja ..

I'm working on macbook.

**Comment by arthaud** [comment]
Hi @hiraditya,

You need to install ikos before you can run the tests. Try `ninja install` if you haven't done it already.

Once installed, you will need to add the ikos directory in your PATH.
If `ikos --version` works as expected, then `ninja test` should work too.

**Comment by hiraditya** [comment]
Thanks! Now 6 tests are passing.

28/33 Test #28: boa ................................   Passed   16.93 sec
      Start 29: dbz
29/33 Test #29: dbz ................................   Passed    0.54 sec
      Start 30: mem
30/33 Test #30: mem ................................   Passed   10.19 sec
      Start 31: null
31/33 Test #31: null ...............................   Passed    2.60 sec
      Start 32: prover
32/33 Test #32: prover .............................   Passed   15.06 sec
      Start 33: uva
33/33 Test #33: uva ................................   Passed    5.81 sec

**Comment by arthaud** [comment]
Cool!

For the other ones, you just need to build the verifier passes, see https://github.com/NASA-SW-VnV/ikos#running-the-tests

**Comment by hiraditya** [comment]
Thank you very much! it all works now. It would be good to add the verifier targets to `all`.

**Comment by arthaud** [comment]
These are only necessary to run the tests. It would be better to build them whenever the user runs `make test`. This will be improved in the next version ;)

Thanks,
Maxime
