### ISSUE TITLE
error: unexpected file extension

### ISSUE THREAD

**Issue by Earnestly** [NASA-SW-VnV/ikos#103]
Many C++ projects use `.cc` and `.hh` but ikos doesn't seem to recognise these "extensions".

Others include `.h`, `.hpp`, `.hxx`, `.cxx`, etc.  Ironically it only seems to recognise `.cpp` but that is a C preprocessor file.

**Comment by arthaud** [comment]
Thanks for the report, I will add support for these "extensions".

By the way, `.cpp` is considered as a c++ file by clang.

```
$ echo "int main() {}" > test.cpp
$ clang -v test.cpp
clang -v test.cpp
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/marthaud/Homebrew/opt/llvm/bin
 "/Users/marthaud/Homebrew/Cellar/llvm/7.0.1/bin/clang-7" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /Users/marthaud/Homebrew/Cellar/llvm/7.0.1/lib/clang/7.0.1 -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /tmp -ferror-limit 19 -fmessage-length 204 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.13.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/9g/hvg_xszs3q79k8tvtqhm_q5s5y3dxb/T/test-fefd56.o -x c++ test.cpp
```
See the `-x c++` at the end.

**Comment by Earnestly** [comment]
Yes, `.cpp` is common on Windows because they didn't have the legacy of C to deal with.  Software like `make` had to use `.cc` instead to avoid clobbering existing implicit rules.

**Comment by arthaud** [comment]
Sure, but ikos can be given a LLVM bitcode file (`.bc`), in which case it has to run different commands.

How do you suggest handling that situation without checking the extension?

**Comment by arthaud** [comment]
By the way, clang does the same thing:
https://github.com/llvm-mirror/clang/blob/master/lib/Frontend/FrontendOptions.cpp

For unknown extensions, it forwards the file to the linker, which fails with a cryptic error.

**Comment by practicalswift** [comment]
Using the same mapping as `clang` is probably the most user-friendly way to handle this.

That is what I would expect at least :-)

**Comment by Earnestly** [comment]
@practicalswift Good call, that's a fair compromise.  Thanks
