### ISSUE TITLE
Unsupported dwarf encoding for llvm DIBasicType

### ISSUE THREAD

**Issue by alcinos** [NASA-SW-VnV/ikos#112]
I get the following error while analysing kdenlive:
```
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-y772mmum/kdenlive.pp.bc: error: unsupported dwarf encoding for llvm DIBasicType
ikos: error: a run-time error occurred
```

I'd be happy to send the bc file, but it's big (56MB after zip compression), so I can't send it here. Open to alternative posting options.

If that makes a difference, I'm building with some sanitizers from clang enabled (namely `-fsanitizer=address,fuzzer-no-link`)

**Comment by arthaud** [comment]
Hi @alcinos,

Please try again without using clang sanitizers. This is currently not supported.

**Comment by arthaud** [comment]
Any news about this?

**Comment by alcinos** [comment]
Hello, sorry for the delay
Finally got around rebuilding everything without the sanitizers, and it appears to give the same crash.

**Comment by arthaud** [comment]
This should be fixed now, thanks for the bug report.
