### ISSUE TITLE
llvm-config failed with status: No such file or directory

### ISSUE THREAD

**Issue by KCKH** [NASA-SW-VnV/ikos#118]
Unable to install analyzer `llvm-config failed with status: No such file or directory`.
I found llvm-config-6.0 in my system (Ubuntu 18.4.02)

Here is my comment:
```
cmake -DCMAKE_INSTALL_PREFIX=../anazlyer \
-DLLVM_CONFIG_EXECUTABLE=../../../../../usr/bin/llvm-6 \
-DCORE_ROOT=../core/ \
-DAR_ROOT=../ar/ \
-DFRONTEND_LLVM_ROOT=../frontend/ \
..
```

This is error:
```
CMake Error at cmake/FindLLVM.cmake:56 (message):
  llvm-config failed with status: No such file or directory
Call Stack (most recent call first):
  cmake/FindLLVM.cmake:61 (run_llvm_config)
  frontend/llvm/CMakeLists.txt:118 (find_package
```
Is there any wrong? How to solve this? Thank

**Comment by arthaud** [comment]
Hi @KCKH,

`-DLLVM_CONFIG_EXECUTABLE=` requires an absolute path to the `llvm-config` executable, not a relative path.
Also, `llvm-config-6.0` is for LLVM 6. IKOS requires LLVM 8.

Please read [doc/install/UBUNTU_18.04.md](https://github.com/NASA-SW-VnV/ikos/blob/master/doc/install/UBUNTU_18.04.md) for installation instructions on Ubuntu 18.04.

**Comment by KCKH** [comment]
Thanks, I will check it again.
