### ISSUE TITLE
Feature request: Super quiet mode (-qq)

### ISSUE THREAD

**Issue by practicalswift** [NASA-SW-VnV/ikos#122]
When running `ikos` to quickly check a program I frequently find myself doing the equivalent of:

```
$ ikos -Wno-some-warning-clang-already-told-me-about \
    -Wno-another-warning-clang-already-told-me-about --rm-db -f text --log none \
    --display-summary no --display-times no file-to-test.c 2>&1 | grep -vE "^# Results"
```

This forces `ikos` to be totally quiet unless it finds something that `clang` does not. Any findings would be written to the console (without pagination) and not leave any files on disk.

The `-Wno-some-warning-clang-already-told-me-about -Wno-another-warning-clang-already-told-me-about` would be solved by the requested `-w` flag (see #121).

Would it be possible to add say `-qq` that would achieve the rest?

Assuming `ikos` doesn't find any potential issues in`file-to-test.c` I would like:

```
$ ikos -qq file-to-test.c
$
```

That would be excellent! :-)

**Comment by arthaud** [comment]
Hi @practicalswift,

First, I will remove the `# Results` if `--display-summary=no` and `--display-times=no`.

Then, I'm wondering if `-q` should also trigger `--display-summary=no --display-times=no`. I think it shouldn't trigger `-w` since having compiler warnings is a good default.

If so, do we really need `-qq`? It would just be an alias for `-w -q`. And do you also want `-qq` to trigger `--rm-db`?

Tanks.

**Comment by practicalswift** [comment]
> First, I will remove the # Results if --display-summary=no and --display-times=no.

Great!

> Then, I'm wondering if -q should also trigger --display-summary=no --display-times=no.

Yes, that would be logical IMO.

> I think it shouldn't trigger -w since having compiler warnings is a good default.

Makes sense!

> If so, do we really need -qq? It would just be an alias for -w -q. And do you also want -qq to trigger --rm-db?

That's a good point: `-w -q` would then do everything I want except leaving the filesystem unchanged after its run.

It's something about the verbosity of `--rm-db` that makes me forget it every time :-)

Perhaps there could be a short argument name for it?

It is probably just me: but when first testing out `ikos` I remember being a little bit surprised a.) that the database was written to disk by default and b.) that a "generic" filename was used for the database file. I quickly got used to that though :-)

**Comment by arthaud** [comment]
Yes, I'm always questioning that design choice.

Maybe the output database should be removed by default?
When running tests and analyzing small files I often don't care about the output database.
When I analyze a big project, it is convenient to have the generated `output.db` to examine it. If we remove the output database by default, then that means we have to generate all the warnings on the terminal, that would be overwhelming if you have hundreds of warnings.

**Comment by arthaud** [comment]
Using c08f58f99ad67ffd35d4e6c6d28850967e3d5931, you should be able to reduce you command to:
```
$ ikos -w -q --rm-db -f=text file-to-test.c
```

**Comment by practicalswift** [comment]
@arthaud Thanks! I'm now using:

```
$ ikos -w -q --rm-db -f=text "file-to-test.c" | grep -vE '^No entries.$'
```

Would it be possible to get rid of the "No entries." output in `-q` is passed? :-)

**Comment by arthaud** [comment]
"No entries" won't be printed if you are using `-f=text`.

**Comment by arthaud** [comment]
Do you have more requests or can I close this?

**Comment by practicalswift** [comment]
Thanks for addressing this. I think we are good for now. Thanks!
