### ISSUE TITLE
Taking a long time to execute the constructor of OutputDatabase

### ISSUE THREAD

**Issue by wutianba** [NASA-SW-VnV/ikos#14]
Ikos(built by cygwin or mingw32) takes a long time to execute the OutputDatabase‘s constructor(analyzer/src/database/output.cpp : 49) on my computer. Even the program below takes 5-6s. Is this normal, are there any suggestions?
```c++
int main() {
  return 0;
}
```

```
clang                                   : 0.148 sec
ikos-analyzer                           : 5.581 sec
ikos-analyzer.check.main                : 0.000 sec
ikos-analyzer.fixpoint-profile-analysis : 0.000 sec
ikos-analyzer.liveness-analysis         : 0.000 sec
ikos-analyzer.llvm-to-ar                : 0.000 sec
ikos-analyzer.load-bc                   : 0.002 sec
ikos-analyzer.simplify-cfg              : 0.000 sec
ikos-analyzer.simplify-upcast-comparison: 0.000 sec
ikos-analyzer.type-checker              : 0.000 sec
ikos-analyzer.unify-exit-nodes          : 0.000 sec
ikos-analyzer.value-analysis            : 0.001 sec
ikos-analyzer.value.main                : 0.000 sec
ikos-analyzer.verify-bc                 : 0.000 sec
ikos-pp                                 : 0.056 sec
```

**Comment by arthaud** [comment]
Hi @wutianba,

I had a similar issue but it was fixed. IKOS was very slow if you ran it in a folder with an existing `output.db`. `OutputDatabase` would use `DROP TABLE` on each table, which can be pretty slow if your database is big (i.e, > 100Mo). I fixed it by just removing automatically the existing `output.db` before the analysis, see [analyzer.py](https://github.com/NASA-SW-VnV/ikos/blob/47d941e12b9607947a656482c960715b666a2aac/analyzer/python/ikos/analyzer.py#L571).

Regarding your issue, I don't really know what could be wrong. Are you using any specific option? Is your hard-drive having issues lately? It would help to know exactly which source line is slow. Maybe you could try to use a profiler like gprof?

**Comment by wutianba** [comment]
Thinks for your reply. @arthaud 
I did not notice that this might be caused by the database.
Using journal seems to be very slow in my sqlite3 library(or in windows). When I close the journal in `DbConnection::DbConnection(std::string filename)` as blow, the speed will be faster.
``` C++
sqlite3_exec(this->_handle, "PRAGMA journal_mode = OFF", nullptr, nullptr, nullptr);
```
Also, creating in-memory database and using `sqlite3_backup_init()` in `DbConnection::~DbConnection()` seems a better way. It is more faster in my computer.

**Comment by arthaud** [comment]
I'm still trying to understand the problem. I have a Windows virtual machine running IKOS and I don't have any issue.

I think your suggestions could probably make the database faster, but it is unrelated to your problem. 5 seconds to write a few kilobytes in a database is just not normal. As I can't reproduce the issue myself I can only recommend you to profile IKOS properly to understand where these 5 seconds are spent.

Regarding your suggestions:
- I will investigate using `PRAGMA journal_mode = OFF` next week. It seems like the database journal is pretty useless for our use-case;
- I already thought about using an in-memory database, but I am concerned about analyzing big source codes. The database can end up being pretty big, since all the checks (even safe) are stored.

Thanks.

**Comment by wutianba** [comment]
This is because using the journal may create and delete output.db-journal again and again.
I don't know the real reason why sqlite3 does this.
If the in-memory database is not applicable, it may be a good idea to use `PRAGMA synchronous = OFF` instead of the default safe and slow `PRAGMA synchronous = FULL`.
A small question, what virtual machine are you using? I have tried it on many different windows systems and machines. I don't confirm if it is some default configuration of windows (such as windows defender) caused the issue.
By the way, I have profiled IKOS 1.3 by visual stadio and fixed it. It seems to be the same problem.

**Comment by arthaud** [comment]
> A small question, what virtual machine are you using? I have tried it on many different windows systems and machines. I don't confirm if it is some default configuration of windows (such as windows defender) caused the issue.

I have a virtual machine running Windows 10 (1803), with MSYS2 and MinGW, and IKOS runs without any problem.
Actually, I finally reproduced your bug by running an old Windows XP + MSYS2 + MinGW. I will investigate this.

> This is because using the journal may create and delete `output.db-journal` again and again.
> I don't know the real reason why sqlite3 does this and why it is very slow.

Do you confirm that using `PRAGMA journal_mode = OFF` fixes the problem for you?

> If the in-memory database is not applicable, it may be a good idea to use `PRAGMA synchronous = OFF` instead of the default safe and slow `PRAGMA synchronous = FULL`.

I will see if I can add this too.

> By the way, I have profiled IKOS 1.3 by visual stadio and fixed it. It seems to be the same problem.

I'm curious to know how you managed to compile IKOS with Visual Studio. How did you get all the dependencies (GMP, LLVM, etc)? What shell did you use? For now I only tried MinGW.

**Comment by wutianba** [comment]
> I have a virtual machine running Windows 10 (1803), with MSYS2 and MinGW, and IKOS runs without any problem.
Actually, I finally reproduced your bug by running an old Windows XP + MSYS2 + MinGW. I will investigate this.

Using Windows 10 or Windows XP with MinGW32 or old version of Cygwin have the problem, It seems because of the version of sqlite3 library.
> Do you confirm that using PRAGMA journal_mode = OFF fixes the problem for you?

Yes, It will be fast and not create output.db-journal at all. But `PRAGMA synchronous = FULL` will be faster.

> I'm curious to know how you managed to compile IKOS with Visual Studio. How did you get all the dependencies (GMP, LLVM, etc)? What shell did you use? For now I only tried MinGW.

I compile all dependencies(without apron) into windows native program on visual studio 2017(platform toolset = v141_xp). And change many codes that v141_xp or windows can not support. But IKOS2 use many grammar that msvc can not support. Then I give up to do the same things.

**Comment by arthaud** [comment]
Thanks @wutianba,

So, I tried using `PRAGMA journal_mode = OFF` only and it was still very slow (3 seconds instead of 10).
Then, I added `PRAGMA synchronous = OFF` and it seems to fix the issue.

I will push the patch. Feel free to reopen the issue if you still have the problem.
