### ISSUE TITLE
Please add a COPYING file

### ISSUE THREAD

**Issue by lovesegfault** [NASA-SW-VnV/ikos#147]
I am attempting to package Ikos to Gentoo, but due to the unconventional non-free license and the lack of a txt version of it in the repo, I cannot. Since #42 seems stuck, it'd like to request for the repo to either:
1. Change LICENSE to a txt file
2. Add a COPYING file with the transcription of LICENSE.pdf

c.c. https://bugs.gentoo.org/686650

Thank you

**Comment by arthaud** [comment]
Hi @lovesegfault,

Apparently, the lawyers don't have a text version and they recommend to include the PDF in the repository. What is the problem with the PDF version exactly?

By the way, thanks for trying to package IKOS on Gentoo.

**Comment by lovesegfault** [comment]
I am not entirely sure why a text version is needed, but I went ahead and converted the PDF one to text, and perhaps the lawyers can approve it. 

I used pdfminer to yield a raw version, and then edited side-by-side with the original, reflowing text to 80 char lines and proof reading in the end.

[LICENSE.txt](https://github.com/NASA-SW-VnV/ikos/files/3470678/LICENSE.txt)

**Comment by lovesegfault** [comment]
Here's a more heavily indented version that I suspect the lawyers might prefer :) 

[LICENSE.txt](https://github.com/NASA-SW-VnV/ikos/files/3470706/LICENSE.txt)

**Comment by Petross404** [comment]
> By the way, thanks for trying to package IKOS on Gentoo.

We need this kind of quality software on Gentoo. ;)

**Comment by arthaud** [comment]
Thank you for your work @lovesegfault.

I got the approval to add the transcript of the license in the repository.

**Comment by lovesegfault** [comment]
Awesome, thanks @arthaud!
