### ISSUE TITLE
How to get the llvm bit code line number as output?

### ISSUE THREAD

**Issue by arnab-security** [NASA-SW-VnV/ikos#148]
Currently the tool gives source code line number as output wherever a warning or error is present. Is it possible to get the llvm bit code line number instead of or in addition to the current source code line number? If yes, kindly tell me what changes need to be done and in which file.

**Comment by arthaud** [comment]
Hi @arnab-security,

What do you mean by llvm bitcode line number? Are you referring to the line number within the text representation of the llvm bitcode, generated with `opt -S` or `--display-llvm`? There is no easy way to get this number within llvm.

**Comment by arnab-security** [comment]
I mean if it is possible to get the LLVM bitcode line instead of or in addition to the source code line as output. I know that there is an option to get the AR code line but I want to get the bitcode line.

**Comment by arthaud** [comment]
I'm sorry, what existing option are you talking about?

I'm confused, you previously asked for the code line **number** and now ask for a code line. 

Are you asking for the textual representation of the llvm instruction?

**Comment by arnab-security** [comment]
The current option to check the AR line is --display-checks=fail. If I get the bitcode line number, I can get the code present in that line also. And in both times, I mean the human readable bit code. Of course, it is easy to get the human readable bitcode from raw bitcode. Basically, I am trying to use the output of ikos, i.e. the warnings in another symbolic tool KLEE. The current source code lines cannot be used and I think that I can use bitcode lines in this another tool.

**Comment by arthaud** [comment]
The option `--display-checks` is handled by the checkers.

For instance, `BufferOverflowChecker` has a method `display_mem_access_check`:
https://github.com/NASA-SW-VnV/ikos/blob/c211b700c617551ee92b17d42c210d9bb5fadf63/analyzer/src/checker/buffer_overflow.cpp#L1402

The easiest solution is probably to change the implementation of the `Checker::display_stmt_location()` method:
https://github.com/NASA-SW-VnV/ikos/blob/c211b700c617551ee92b17d42c210d9bb5fadf63/analyzer/src/checker/checker.cpp#L70-L73

Try something like this:
```c++
void Checker::display_stmt_location(LogMessage& msg, ar::Statement* s) const {
  msg << color::bold() << source_location_string(s, _ctx.wd) << ": "
      << color::off();

  if (!s->has_frontend()) {
    return; // not associated to a llvm instruction
  }

  auto inst = s->frontend< llvm::Value >();
  llvm::raw_os_ostream stream(msg.stream());
  inst->print(stream);
  msg << ": ";
}
```

**Comment by arnab-security** [comment]
This change displays the LLVM line along with the invariant. But the output.db does not have these lines.
 
Is it possible to only get the LLVM line and omit the invariant in the display and is it possible to get it in the output.db file?

**Comment by jogolden** [comment]
Omit invariant here or in that specific checker...
https://github.com/NASA-SW-VnV/ikos/blob/master/analyzer/include/ikos/analyzer/checker/checker.hpp#L137

The line number is located here If Im not mistaken...
https://github.com/NASA-SW-VnV/ikos/blob/master/analyzer/include/ikos/analyzer/checker/checker.hpp#L164
https://github.com/NASA-SW-VnV/ikos/blob/master/analyzer/src/checker/checker.cpp#L70

The output.db is already automatically generated when you print using the log mechanisms because of the llvm command line init here?
https://github.com/NASA-SW-VnV/ikos/blob/5be698e4ffa2bf8583d028c62ada170379ae2ba0/analyzer/src/ikos_analyzer.cpp#L113

I like this repository, source code is very well organized and easy to read.

**Comment by arthaud** [comment]
> Is it possible to only get the LLVM line and omit the invariant in the display and is it possible to get it in the output.db file?

Using `--display-checks=fail --display-inv=no`, you will get the checks and not the invariants.

The `--display-checks` and `--display-inv` options are meant for debugging/logging and do not affect the output database.

It could be possible to add the llvm instruction in the output database but there will be some work to do. For instance, you could add a column to the `statements` table. You would have to change all of the following files:
* https://github.com/NASA-SW-VnV/ikos/blob/708ebe200473dd4e13b817f43a3bc7d52ac6f47e/analyzer/src/database/table/statements.cpp#L55
* https://github.com/NASA-SW-VnV/ikos/blob/708ebe200473dd4e13b817f43a3bc7d52ac6f47e/analyzer/src/database/table/statements.cpp#L66
* https://github.com/NASA-SW-VnV/ikos/blob/708ebe200473dd4e13b817f43a3bc7d52ac6f47e/analyzer/python/ikos/enums.py#L342
* https://github.com/NASA-SW-VnV/ikos/blob/708ebe200473dd4e13b817f43a3bc7d52ac6f47e/analyzer/python/ikos/output_db.py#L198
* https://github.com/NASA-SW-VnV/ikos/blob/708ebe200473dd4e13b817f43a3bc7d52ac6f47e/analyzer/python/ikos/report.py#L654

**Comment by arthaud** [comment]
Any news about this? Should I close the issue?

**Comment by arnab-security** [comment]
Yes, please close this.
