### ISSUE TITLE
Build error: Duplicated definition of strdup in APRON

### ISSUE THREAD

**Issue by Turakar** [NASA-SW-VnV/ikos#150]
I tried to install IKOS according to the documentation for Fedora 29 (my host system). The following command errors:
```
./bootstrap --prefix=../install --builddir=../build
```
I attached the log file: [bootstrap.log](https://github.com/NASA-SW-VnV/ikos/files/3516028/bootstrap.log)

Do you know, what causes these errors?

**Comment by arthaud** [comment]
This is fixed in 7f24ed0e88f197bc6102cbe25a356a21142ffac5.

I have also updated the [installation instructions for Fedora](https://github.com/NASA-SW-VnV/ikos/blob/master/doc/install/FEDORA_29.md).

Thank you.
