### ISSUE TITLE
ikos-scan doesn't work with mpi wrapper compilers

### ISSUE THREAD

**Issue by BenWibking** [NASA-SW-VnV/ikos#155]
I'm attempting to use ikos-scan on a project that calls MPI wrapper compilers instead of the C/C++ compilers directly.

This fails because ikos intercepts the MPI wrapper commands and replaces them with clang compilers, but does not include the MPI header flags needed for a successful parse:
```
../Chombo3.2/lib/src/BaseTools/SPMD.H:31:10: fatal error: 'mpi.h'
      file not found
#include <mpi.h>
         ^~~~~~~
1 error generated.
```

**Comment by arthaud** [comment]
It seems like the MPI wrapper adds many compiler flags.

Could you try to run `mpicc -showme` to get all the flags, and then set `CPPFLAGS` and `LDFLAGS` accordingly? Then running `ikos-scan` should work.

**Comment by ivanperez-keera** [comment]
@BenWibking did you ever get a chance to try what Maxime was proposing (setting the compilation and linking flags via environment variables before calling `ikos-scan`)?

**Comment by BenWibking** [comment]
No, I never got around to this. I'll close this issue, since I probably won't return to this project.
