### ISSUE TITLE
Missing debug information for llvm function

### ISSUE THREAD

**Issue by jmichaelbarker** [NASA-SW-VnV/ikos#157]
I'm attempting to add ikos-scan to the CI for one of our projects currently using coverity, however I'm having an issue running ikos on it project. I'm attempting to run the analysis on a unit test binary, since the project builds to a library (.a) which from what I can tell is unsupported at the moment. However, I run into the following issue when attempting to run the analysis:

```Analyze test/main_test/agent_main? [Y/n] y
[*] Running ikos test/main_test/agent_main.bc -o test/main_test/agent_main.db
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-2MiE27/agent_main.pp.bc: error: missing debug information for llvm function __llvm_gcov_init
ikos: error: a run-time error occurred
```

Any help would be appreciated, and I'll gladly provide as much additional information as possible (however, this is a company project so I won't be able to upload code samples due to IP concerns).

**Comment by arthaud** [comment]
The problem is that IKOS cannot find debug information about the `__llvm_gcov_init` function.

This is a special function added by clang for coverage purposes.

Are you compiling with specific flags to enable coverage reports (e.g, `-fprofile-instr-generate` or `-fcoverage-mapping`)? You should disable these compiler flags when using `ikos-scan` and it should fix the problem.

**Comment by arthaud** [comment]
Any news about this?

**Comment by ivanperez-keera** [comment]
Circling back.

@jmichaelbarker, did you ever get a chance to try what Maxime was saying (compiling with coverage reports disabled)?

**Comment by ivanperez-keera** [comment]
Given that a proposed solution was suggested by @arthaud and we have not heard back in over  2 years, I suggest we close this.

**Comment by ivanperez-keera** [comment]
As proposed before, I'm going to close this. If this is still an issue, please re-open. Thanks!
