### ISSUE TITLE
document icos-scan

### ISSUE THREAD

**Issue by nickdesaulniers** [NASA-SW-VnV/ikos#16]
Looks like there's another tool that wasn't in the readme: https://www.reddit.com/r/C_Programming/comments/a5a5nc/ikos_21_an_open_source_static_analyzer_for_c_and_c/ebm1r8i/

**Comment by arthaud** [comment]
Hi @nickdesaulniers,

Thanks for reporting this.

This is actually documented in [analyzer/README.md#analyze-a-whole-project](https://github.com/NASA-SW-VnV/ikos/tree/master/analyzer#analyze-a-whole-project)
There is a link in the main README.md: "Analyze a whole project" at the end of the "How to run IKOS" section.

I'm wondering how we could improve this. Maybe I should move the "Analyze a whole project" in the main README.md? What do you think?

**Comment by nickdesaulniers** [comment]
LGTM, ctrl+f for `ikos-scan` was turning up no hits in the top level README.  Maybe change the bullet to `Analyze a whole project (with ikos-scan)` just so it's grep'able?

**Comment by nickdesaulniers** [comment]
Thanks! I look forward to giving it a shot on Linux kernels used for Android.  I'll try to reach out should we find some bugs with ikos!
