### ISSUE TITLE
Upgrade to LLVM 10

### ISSUE THREAD

**Issue by iamwonseok** [NASA-SW-VnV/ikos#160]
Hi @arthaud, 

I think you already have a plan to upgrade LLVM 11 for IKOS after releasing LLVM 11 officially.
By the way, I just made patch to support LLVM 11 to IKOS for personal reason, since the LLVM 9 does not support various RISC-V's compilation options. If you don't mind could I send PR (support LLVM 11) for IKOS?

**Comment by arthaud** [comment]
Yes, feel free to submit a PR.

**Comment by Petross404** [comment]
Not that I am trying to hijack this issue, but is there any progress on upgrading the llvm requirements?

**Comment by ivanperez-keera** [comment]
IKOS now supports LLVM 14 (See https://github.com/NASA-SW-VnV/ikos/commit/9060838b31a8b08db12c45a3990c286a8e441273).

Can this be closed, @iamwonseok ?

**Comment by iamwonseok** [comment]
Sure.
