### ISSUE TITLE
Optimization removes assertions involving uninitialized variables

### ISSUE THREAD

**Issue by lou1306** [NASA-SW-VnV/ikos#166]
MWE:

```c
#include <ikos/analyzer/intrinsic.h>

int main(void) {
    int x;
    __ikos_assert(x != 1);
    return 0;
}
```

If IKOS analyzes this program with basic optimizations *enabled* (i.e., the default setting), the program is reported as *safe*. If all optimizations are *disabled* via `--opt none`, then the program is reported as *potentially unsafe* (which is the expected outcome).
The summary reports "Total number of checks: 0" when optimizations are enabled, so I guess that the assertion statement is optimized away?

I think this is an issue, because the end user might not realize that optimizations may alter the outcome of a verification task (personally, I wasn't sure until I worked out this MWE).

## Output logs

<details>
  <summary>Output of `ikos -a prover mwe.c`</summary>

```
[*] Compiling mwe.c
mwe.c:6:17: warning: variable 'x' is uninitialized when used here [-Wuninitialized]
  __ikos_assert(x != 1);
                ^
mwe.c:5:8: note: initialize the variable 'x' to silence this warning
  int x;
       ^
        = 0
1 warning generated.
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
[*] Running liveness analysis
[*] Running widening hint analysis
[*] Running interprocedural value analysis
[*] Analyzing entry point 'main'
[*] Checking properties for entry point 'main'

# Time stats:
clang        : 0.029 sec
ikos-analyzer: 0.009 sec
ikos-pp      : 0.007 sec

# Summary:
Total number of checks                : 0
Total number of unreachable checks    : 0
Total number of safe checks           : 0
Total number of definite unsafe checks: 0
Total number of warnings              : 0

The program is SAFE

# Results
No entries.

```  

</details>

<details>
  <summary>Output of "ikos -a prover --opt none mwe.c"</summary>

```
[*] Compiling mwe.c
mwe.c:6:17: warning: variable 'x' is uninitialized when used here [-Wuninitialized]
  __ikos_assert(x != 1);
                ^
mwe.c:5:8: note: initialize the variable 'x' to silence this warning
  int x;
       ^
        = 0
1 warning generated.
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
[*] Running liveness analysis
[*] Running widening hint analysis
[*] Running interprocedural value analysis
[*] Analyzing entry point 'main'
[*] Checking properties for entry point 'main'

# Time stats:
clang        : 0.028 sec
ikos-analyzer: 0.010 sec
ikos-pp      : 0.007 sec

# Summary:
Total number of checks                : 1
Total number of unreachable checks    : 0
Total number of safe checks           : 0
Total number of definite unsafe checks: 0
Total number of warnings              : 1

The program is potentially UNSAFE

# Results
mwe.c: In function 'main':
mwe.c:6:3: warning: assertion could not be proven
  __ikos_assert(x != 1);
  ^
```  

</details>

PS. Thank you for maintaining IKOS! 😃

**Comment by arthaud** [comment]
Hi @lou1306, thanks for reaching out.
As you said, this is most likely because basic optimizations simply remove the assertion. This is indeed annoying but there isn't much we can do about it.
Have you tried using `ikos -a uva` (uninitialized variable analysis)?
Also, I'm pretty sure this should be caught by basic compiler warnings. Have you tried compiling with `clang -Weverything`?

**Comment by lou1306** [comment]
Yes, gcc and clang do raise a `-Wuninitialized` warning.

I am comparing several C verification tools and there are different degrees of tolerance with respect to uninitialized variables (among other things): in the case of this MWE, some tools would assume that `x` has a nondeterministic value and report the program as unsafe. So, I just wanted to make sure that the outcomes I reported were the expected behavior for IKOS. Thank you for clearing this up.
