### ISSUE TITLE
Please support oneTBB

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#169]
They are replacing ```TBB``` with a new generation, ```oneTBB```, and ikos fails to build:
http://box.martymac.org/FreeBSD-Packages/data/FBSD122amd64-tbb-migr/2021-01-13_22h35m17s/logs/errors/ikos-3.0_3.log

Thanks,
Yuri

**Comment by keck-in-space** [comment]
Did you find any solution to this? I can't get IKOS to build either.

**Comment by yurivict** [comment]
ikos-3.1 builds fine with onetbb.

**Comment by keck-in-space** [comment]
Interesting. I'm trying with IKOS 3.1 but getting the same error shown in your log. I installed onetbb using the installer [here](https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#onetbb), but CMake can't find it using the FindTBB.cmake file included in IKOS 3.1.

**Comment by yurivict** [comment]
@keck-in-space What cmake version are you using?

**Comment by keck-in-space** [comment]
Great question. I think I actually found the solution in a PR https://github.com/NASA-SW-VnV/ikos/pull/164. I'm on RHEL 8 so I'm using an outdated CMake (cmake version 3.20.2).

**Comment by arthaud** [comment]
If cmake cannot find TBB automatically, you can provide `-DTBB_ROOT=/path/to/tbb` when calling cmake. It must be a path X such that `X/tbb/tbb.h` exists.
