### ISSUE TITLE
How to use ikos in jenkins?

### ISSUE THREAD

**Issue by ji0859** [NASA-SW-VnV/ikos#172]
How can I use ikos in jenkins?
When creating the project in Jenkins, ikos was run by selecting an execution shell in the build part.

For example 
```
#!/bin/sh
ikos /var/jenkins_home/workspace/git/loop.c > text.txt
```
Then I tried to build but they couldn't find ikos.

**Comment by Petross404** [comment]
`which ikos`. Paste the output to the script instead of plain ikos.

**Comment by ji0859** [comment]
Thanks to you, I solved it. :)

**Comment by Petross404** [comment]
Glad it helped ;)
