### ISSUE TITLE
Support the JUnit XML format for IKOS output 

### ISSUE THREAD

**Issue by mjeronimo** [NASA-SW-VnV/ikos#178]
In order to integrate with the Jenkins CI/CD tool, it would be helpful to have IKOS output detected issues in the JUnit XML format, which is understood by Jenkins.

**Comment by ivanperez-keera** [comment]
This feature was added in https://github.com/NASA-SW-VnV/ikos/commit/0053cb5f93e3e8a3dca3c97bb1694c164373b2c9.

Please re-open if something else related to the JUnit XML format is needed.
