### ISSUE TITLE
Generating a .egg file

### ISSUE THREAD

**Issue by mjeronimo** [NASA-SW-VnV/ikos#185]
To be compatible with easy_install, it would be nice to have the build process generate the final .egg file (and not just the egg-info directory). Otherwise, I'm having to zip the contents of the directory into a .egg file before installing.

**Comment by ivanperez-keera** [comment]
Please see https://github.com/space-ros/space-ros/issues/29#issuecomment-1785518085.

I can't get to the state where the `egg-info` directory would be produced, nor can I see in Space ROS where this is happening (everything's automated via `ros-dep`, I suspect).

If this is still an issue, please let us know.

**Comment by ivanperez-keera** [comment]
I just sent a PR with a proposed change @mjeronimo . You are welcome to try it.
