### ISSUE TITLE
Consider migrating from Travis to another CI system such as GitHub Actions

### ISSUE THREAD

**Issue by mbrukman** [NASA-SW-VnV/ikos#186]
This repo still has a `.travis.yml` and a Travis CI status badge (showing an error) in the README, but since [Travis stopped supporting open-source projects](https://blog.travis-ci.com/oss-announcement) a while ago, the last time a build ran on this repo was about a year ago: https://travis-ci.org/github/NASA-SW-VnV/ikos

Please consider migrating to [GitHub Actions](https://github.com/features/actions) ([docs](https://docs.github.com/en/actions)) (since it's provided by GitHub and is free for open-source projects, so it's easy to set up) or another CI system of your choice, as currently, no CI is running on PRs for this project.

FWIW, I'm not affiliated with either Travis or GitHub.

**Comment by ivanperez-keera** [comment]
Thank you for the suggestion and your patience, @mbrukman.

I think this is a good idea.

Addressing this will help us on other fronts too. Several other issues that users are having have to do with installation in different OSs, some of which I don't even have available to try.

I'm looking into this issue now to first evaluate how much work this would be. If it's doable by the time of the next release, I'll assign it to the milestone.

**Comment by ivanperez-keera** [comment]
I almost got the linux build working, but I can't for the life of me make it find the ikos python module.

I've set `PYTHONPATH`, but it's still not finding. I'm sure it's trivial and I'm just not seeing it. If any if you do, please let me know.

**Comment by ivanperez-keera** [comment]
I am almost certain that this is because we are not using pip to install the application. If I install it manually, it works:
```
# ikos --version
error: could not find ikos python module
error: see TROUBLESHOOTING.md
# apt-get install python3-pip
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  build-essential bzip2 dirmngr dpkg-dev fakeroot gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm javascript-common
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl libassuan0 libdpkg-perl libexpat1-dev libfakeroot libfile-fcntllock-perl libjs-jquery
  libjs-sphinxdoc libjs-underscore libksba8 liblocale-gettext-perl libnpth0 libpython3-dev libpython3.10 libpython3.10-dev lto-disabled-list pinentry-curses python3-dev
  python3-wheel python3.10-dev xz-utils
[...]
# cd ~/ikos/build/analyzer/python 
# pip install .
Processing /root/ikos/build/analyzer/python
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: ikos
  Building wheel for ikos (setup.py) ... done
  Created wheel for ikos: filename=ikos-3.1-py3-none-any.whl size=65218 sha256=b6a015718147c84448934416026cda71112bd789a7e8a9394f44923542598fde
  Stored in directory: /tmp/pip-ephem-wheel-cache-9datso8y/wheels/f7/af/97/fb79691d865802df48db9c5cc70ef91a7ddc894d189037841e
Successfully built ikos
Installing collected packages: ikos
Successfully installed ikos-3.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# cd
# ikos --version
ikos 3.1
Copyright (c) 2011-2019 United States Government as represented by the
Administrator of the National Aeronautics and Space Administration.
All Rights Reserved.
```

**Comment by ivanperez-keera** [comment]
Ok, I switched from `easy_install` to pip and that solved the issue. I'll need to test it on all platforms, including windows and mac, as well as with python2, and it if works we can merge that separately.

**Comment by ivanperez-keera** [comment]
I've just sent a PR #236 that addresses this. For it to work, you have to merge the changes in #234 and #235 first.

**Comment by mbrukman** [comment]
Thank you, @ivanperez-keera!
