### ISSUE TITLE
Interprocedural analysis

### ISSUE THREAD

**Issue by jumormt** [NASA-SW-VnV/ikos#190]
Hi,

Does ikos support context-sensitive value-flow analysis? The current interprocedural analysis seems to analyze each function separately using FunctionFixpoint iterator without connecting caller-callee.

Kind Regards

**Comment by arthaud** [comment]
> Does ikos support context-sensitive value-flow analysis? The current interprocedural analysis seems to analyze each function separately using FunctionFixpoint iterator without connecting caller-callee.

Curious what made you say that? IKOS performs its analysis top-down, from main to its callees, and so on. In a way, you can think of it as if it was inlining everything inside main. Hence it is a context-sensitive interprocedural analysis. The way it is done is not super scalable though, so you will it problems for 20k+ lines of code.

It does use a pointer analysis that is not context-sensitive though.

**Comment by jumormt** [comment]
Thanks for your answer.
