### ISSUE TITLE
Support for building on Ubuntu 22.04

### ISSUE THREAD

**Issue by nuclearsandwich** [NASA-SW-VnV/ikos#193]
Update:

Now that ikos supports llvm 14, there are build issues with python recorded in https://github.com/NASA-SW-VnV/ikos/issues/193#issuecomment-1636683997

---

ikos currently requires llvm 9 which is no longer available in Ubuntu 22.04.

LLVM [11](https://packages.ubuntu.com/jammy/llvm-11), [12](https://packages.ubuntu.com/jammy/llvm-12), [13](https://packages.ubuntu.com/jammy/llvm-13), and [14](https://packages.ubuntu.com/jammy/llvm-14) are all packaged in 22.04. As a side note, Debian Bullseye (the current stable release) provides [LLVM 11](https://packages.debian.org/bullseye/llvm-11) and [13](https://packages.debian.org/bullseye/llvm-13) but not 12 and 14 was not yet released.

It looks like the pending work on LLVM 10 has stalled https://github.com/NASA-SW-VnV/ikos/pull/162.
Looking at the above release coverage, 13 would probably the next version to target in order to build on current (and likely at least one future) releases of Debian and Ubuntu.

**Comment by ivanperez-keera** [comment]
@nuclearsandwich we are in LLVM 14 now. Are you able to try again?

If you have a Docker image for this (maybe as part of Space ROS), I can try it quickly as well.

Thanks!

**Comment by ivanperez-keera** [comment]
The following Dockerfile is not Space ROS specific, but still relevant:

https://github.com/NASA-SW-VnV/ikos/issues/171#issuecomment-1625968905

**Comment by ivanperez-keera** [comment]
@nuclearsandwich  Please let me know about this. As far as I can see, ikos is building on jammy which Space ROS is based on. The last release from December supports LLVM 14. If anything else is needed, please let me know. Otherwise, I think we can close this issue.

**Comment by ivanperez-keera** [comment]
Email sent to @nuclearsandwich . Will close in 3 days if no answer is received.

**Comment by nuclearsandwich** [comment]
Thanks for the message, I gave building another go and hit the following error:

```
/src/ikos/b/analyzer/python/setup.py:42: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
Traceback (most recent call last):
  File "/src/ikos/b/analyzer/python/setup.py", line 42, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils.core'
make[2]: *** [analyzer/CMakeFiles/ikos-python.dir/build.make:90: analyzer/python/build/lib/ikos/__init__.py] Error 1
make[1]: *** [CMakeFiles/Makefile2:1644: analyzer/CMakeFiles/ikos-python.dir/all] Error 2
```

If no one is looking at this yet, I think I can at least start a patch to switch away from distutils.

**Comment by ivanperez-keera** [comment]
Thanks @nuclearsandwich 

See this docker file: https://github.com/NASA-SW-VnV/ikos/issues/171#issuecomment-1625968905

It installs distutils manually in this step:

```
# Install all dependencies
RUN apt-get install --yes [... bunch of packages ...] python3-distutils
```

**Comment by nuclearsandwich** [comment]
> It installs distutils manually in this step:

Thanks for the tip! (What are we both doing on a Friday night?)

Distutils is long [deprecated](https://docs.python.org/3/library/distutils.html) and slated for removal in Python 3.12. In truth, I thought it was already gone which is I why I offered to submit a patch. Do you think it makes more sense to proceed with distutils for Ubuntu 22.04 or address the underlying issue? Python 3.12 is, I believe, going to be released in October and will almost certainly also be used for Ubuntu 24.04 in April, so even if we use distutils for Jammy it buys us a half a year or so.

**Comment by ivanperez-keera** [comment]
If it is a simple fix, I'd say let's remove distutils. If it's a bit more complex, we can partition this in two: one issue (and PR) that provides a build for 22.04 and updates the installation instructions, and one issue (and PR) that removes the dependency on distutils (adjusting the installation instructions accordingly).

Partitioning this issue in two makes the whole thing a tiny bit bigger, but it provides an immediate official workaround and it makes it easier to complete and process (because in spite of our Friday night efforts, we are likely to be interrupted by high priority things).

**Comment by nuclearsandwich** [comment]
Sounds good, I'll take a shot over the weekend and see how far I get.

**Comment by ivanperez-keera** [comment]
Whichever decision we make, I think it's safe to plan closing this issue in the next release. I'm assigning this to the next milestone.

**Comment by ivanperez-keera** [comment]
Tagging @nuclearsandwich for awareness.

**Comment by ivanperez-keera** [comment]
I just sent a PR with the proposed change @nuclearsandwich . You are welcome to try it.
