### ISSUE TITLE
it seems that ikos will never reach to a fixpoint when analyze vim project

### ISSUE THREAD

**Issue by phoon0416** [NASA-SW-VnV/ikos#207]
when analyze vim project [https://github.com/vim/vim](https://github.com/NASA-SW-VnV/ikos/issues/url) with IKOS, 
I found that during 12 hours' running, the memory usage of IKOS is kept to 28 percent, and the 
running of IKOS never terminate. To find the culprit of this problem, I did some experiments on IKOS. 
Before elaborate my experiments, I will introduce a piece of code and some concept of IKOS firstly.

As all know, when compute the fixpoint of a cycle in program, we should compare the abstraction 
value of current iteration on the cycle to the previous one. if abstraction value of current iteration 
is less equal to the previous one, that is the fixpoint of this cycle is reached(for simplicity, we just 
considerate the increasing analysis, and ignore the decreasing analysis at this moment). The 
following piece of code of IKOS correspond to mentioned above:
```c++
  /// \brief Check if the increasing iterations fixpoint is reached
  virtual bool is_increasing_iterations_fixpoint(NodeRef head,
                                                 unsigned iteration,
                                                 const AbstractValue& before,
                                                 const AbstractValue& after) {
    ikos_ignore(head);
    ikos_ignore(iteration);

    return after.leq(before);
  }
```
this abstraction value is consist of Uninitialized data flow, Integer data flow, Null Pointer Dereference 
data flow, Points To data flow, Memory Location To Cells data flow, Lifetime dataflow. The leq method 
of abstraction value will apply to every data flow, which cause each data flow call its own leq method, 
if this method of one kind data flow returns true, it means that this kind of data flow reached to fixpoint.

I did the following experiments on IKOS:
1. modify the leq method of Integer dataflow to return true permanently, which means that the 
Integer dataflow always reached to fixpoint. When analyze vim project in this situation, IKOS 
will exhaust entire memory of my machine (64GB) during 12 hours' running,
and it do not terminate
2. modify the leq method of all other dataflows except for Integer dataflow to return true permanently, 
which means that we only need compute Integer dataflow to reach to fixpoint. When analyze vim 
project in this situation, the memory usage of IKOS is kept to 28 percent during 12 hours' running, 
and never terminate.
Based on experiments above, I guess that for vim project, the Integer dataflow cannot reach to 
fixpoint on a specific calling chain. BTW, I use the Interval domain for Integer dataflow.

Any suggestions about this issue ?

**Comment by phoon0416** [comment]
@arthaud

**Comment by arthaud** [comment]
Hi @phoon0416,

A non converge issue is usually due to one of the `leq`, `join` or `widen` operators. In that case it seems like this is due to the numerical domain.
This can be a bit complicated to debug. This is what I would usually do:
* The non convergence is most likely due to a loop somewhere - which corresponds to a cycle in the control flow graph. I would try to find which loop it is. In the function fixpoint, you can start logging which basic block (function/file/line/column etc) is the head of the currently analyzed cycle when the number of iterations is high (say >10): https://github.com/NASA-SW-VnV/ikos/blob/master/analyzer/src/analysis/value/interprocedural/sequential/function_fixpoint.cpp#L151
* In the same function, I would log the `before` and `after` abstract domains, as well as the result of the extrapolation, to see why it keeps growing or it not stable. To converge, we need the last iteration to have `before.widen(after).leq(after)`. I would carefully examine those domains, try to spot the difference.

**Comment by phoon0416** [comment]
Thanks for your reply @arthaud , and sorry for belated response. 
Following your suggestion, I write a simple patch as follows:

```c++
diff --git a/analyzer/src/analysis/value/interprocedural/sequential/function_fixpoint.cpp b/analyzer/src/analysis/value/interprocedural/sequential/function_fixpoint.cpp
index 0aa5ab6..8b4fc22 100644
--- a/analyzer/src/analysis/value/interprocedural/sequential/function_fixpoint.cpp
+++ b/analyzer/src/analysis/value/interprocedural/sequential/function_fixpoint.cpp
@@ -46,6 +46,7 @@
 #include <ikos/analyzer/analysis/pointer/pointer.hpp>
 #include <ikos/analyzer/analysis/value/interprocedural/sequential/function_fixpoint.hpp>
 #include <ikos/ar/format/text.hpp>
+#include <ikos/frontend/llvm/import/source_location.hpp>
 
 namespace ikos {
 namespace analyzer {
@@ -160,6 +161,23 @@ AbstractDomain FunctionFixpoint::extrapolate(ar::BasicBlock* head,
   iteration -= this->_fixpoint_parameters.widening_delay;
   iteration--;
 
+  if (iteration > 10) {
+    ar::Statement* s = nullptr;
+    for (auto it = head->begin(), ie = head->end(); it != ie; it++) {
+      if ((*it)->has_frontend()) {
+        s = *it;
+        break;
+      }
+    }
+    assert(s != nullptr && "this basic block has no corresponding frontend");
+    auto sl = frontend::import::source_location(s);
+    std::cout << "======================================================\n";
+    std::cout << "file: " << sl.file()->getFilename().data() << 
+      " function:" << head->code()->function()->name() <<
+      " line:" << sl.line() << " column:" << sl.column() << std::endl;
+    std::cout << "======================================================\n";
+  }
+
   if (iteration % this->_fixpoint_parameters.widening_period != 0) {
     // Not the period, iteration using join
     return before.join_iter(after);
@@ -175,8 +193,20 @@ AbstractDomain FunctionFixpoint::extrapolate(ar::BasicBlock* head,
         }
       }
 
-      // Iterations using widening until convergence
-      return before.widening(after);
+      auto my_inv = before.widening(after);
+      if (iteration > 10) {
+        // Iterations using widening until convergence
+        std::cout << "-----------------------------------------------------n";
+        std::cout << "before abstract value:\n";
+        before.dump(std::cout);
+        std::cout << "after abstract value:\n";
+        after.dump(std::cout);
+        std::cout << "widen abstract value:\n";
+        my_inv.dump(std::cout);
+        std::cout << "-----------------------------------------------------n";
+        while (1);
+      }
+      return my_inv;
     }
     case WideningStrategy::Join: {
       // Iterations using join until convergence
```

Firstly I am sorry for my inadequate testing last time, and this time 
I prolong the test time to 36 hours (last time just 12 hours), By using ikos 
test the same vim project with all data flows including numerical domain, 
I found two following facts:
- ikos never run into my patch codes
- the memory usage of ikos gradually grows to 92%, it will be killed for out of memory(64G)

Base on this two facts, we can come to a conclusion that ikos can reach to a 
fixpoint with numerical domain in testing vim project, compared to running with data flows 
excluding numerical domain, ikos running with all data flows will spend much more time to 
reach fixpoint.

At last, i want to ask "from your experience, how many source lines can ikos process?", 
since I test vim project(40W lines of code), it will be eventually killed for out of memory 
in my local machine(64G), and it runs over 24hours, BTW, I don't use parallel analysis.

Appreciate for your suggestion again @arthaud

**Comment by arthaud** [comment]
Hi @phoon0416,

We have analyzed code with between 10k to 20k lines of code, especially safety critical software.
It sounds like the vim source code is too big for ikos. It is known that ikos does not scale well beyond 20k lines of code, since it does a top-down interprocedural analysis. It is not a modular analysis unfortunately.

**Comment by phoon0416** [comment]
OK, I got it, and thanks for your reply.
