### ISSUE TITLE
Crashed on my codebase

### ISSUE THREAD

**Issue by ttsiodras** [NASA-SW-VnV/ikos#21]
Just tried this static analyser on my codebase ( https://github.com/ttsiodras/renderer/ ) - and sadly, got a crash:

      CXX      renderer-BVH.o
      CXX      renderer-Loader.o
      CXX      renderer-Raytracer.o
      CXXLD    renderer
      CXX      showShadowMap-showShadowMap.o
      CXX      showShadowMap-Keyboard.o
      CXXLD    showShadowMap
    make[2]: Leaving directory '/home/ttsiod/Github/renderer/src'
    make[1]: Leaving directory '/home/ttsiod/Github/renderer/src'
    make[1]: Entering directory '/home/ttsiod/Github/renderer'
    make[1]: Nothing to be done for 'all-am'.
    make[1]: Leaving directory '/home/ttsiod/Github/renderer'
    Analyze lib3ds-1.3.0/tools/3dsdump? [Y/n] n
    Analyze src/renderer? [Y/n] Y
    [*] Running ikos src/renderer.bc -o src/renderer.db
    [*] Running ikos preprocessor
    [*] Running ikos analyzer
    [*] Translating LLVM bitcode to AR
    ikos-analyzer: /tmp/ikos-j60gqc4k/renderer.pp.bc: error: unexpected null pointer in llvm::DICompositeType with DW_TAG_structure_type or DW_TAG_class_type tag
    ikos: error: a run-time error occured

The code is available in my GitHub repo, so the bug is easy to reproduce.

**Comment by ttsiodras** [comment]
> I guess you are running Linux?

Yes. Arch Linux, to be precise. 
My renderer depends also on libSDL - but I don't believe this has anything to do with the crash: as you can see from the log, there's a null pointer exception when the `ikos-analyser` tries to parse the generated LLVM bytecode.

**Comment by arthaud** [comment]
Alright, I pulled an Arch Linux docker container, and now I got another error:

```
[root@88cd89ccbbe5 renderer]# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /root/renderer/build-aux/missing aclocal-1.15
/root/renderer/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:483: aclocal.m4] Error 127
```
I have autoconf 1.16, so the command `aclocal-1.16` exists.

**Comment by arthaud** [comment]
Alright, I figured I had to run `autoreconf -i -f`. Still investigating.

**Comment by ttsiodras** [comment]
I don't get such an error...
Can you try from the release tarball (available under the "Releases" tab)? I just did this:

    $ wget https://github.com/ttsiodras/renderer/archive/v2.3b.tar.gz
    $ tar xpvf v2.3b.tar.gz
    $ cd renderer-2.3b/
    $ ikos-scan --version
    ikos 2.1
[crash.log](https://github.com/NASA-SW-VnV/ikos/files/2679690/crash.log)

    Copyright (c) 2011-2018 United States Government as represented by the
    Administrator of the National Aeronautics and Space Administration.
    All Rights Reserved.
    $ ikos-scan ./configure
    $ ikos-scan make

....and this reproduces the crash. I also attach the log of the last command (the one that crashes).

In case it matters, I built ikos from the master 2 days ago - commit 009dd22250f0bcef4caab4bb10fd544cfb9f0dd0 .

**Comment by arthaud** [comment]
Could you send me `src/renderer.bc`?

With my luck, I got another error in ikos:
```
[root@88cd89ccbbe5 renderer-2.3b]# ikos src/renderer.bc
[*] Running ikos preprocessor
[*] Running ikos analyzer
[!] ikos was compiled in debug mode, the analysis might be slow
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-7hri6z90/renderer.pp.bc: error: unsupported llvm::Instruction (opcode: insertelement)
ikos: error: a run-time error occured
```

**Comment by ttsiodras** [comment]
Sure - attached below.
[renderer.bc.gz](https://github.com/NASA-SW-VnV/ikos/files/2681728/renderer.bc.gz)

**Comment by arthaud** [comment]
I made a new issue with this bug, see #41 

We can keep this issue open, so that I remember to try ikos on renderer once #41 is fixed.

**Comment by arthaud** [comment]
Bug #41 was fixed in 8c9e9fbba7b487bb85a0a42627c35617797e70bb.

Now, I'm getting the following error:
```
$ ikos renderer.bc
[*] Running ikos preprocessor
[*] Running ikos analyzer
[!] ikos was compiled in debug mode, the analysis might be slow
[*] Translating LLVM bitcode to AR
ikos-analyzer: /var/folders/9g/hvg_xszs3q79k8tvtqhm_q5s5y3dxb/T/ikos-TcPRlA/renderer.pp.bc: error: unsupported llvm::Instruction in infer_type_hint_use() (opcode: shufflevector)
ikos: error: a run-time error occurred
```
See issue #51

**Comment by arthaud** [comment]
I fixed #51 with dce0cde78748a6702a7da189295ac2b9b61dfc66.

I'm now getting another error:
```
$ ikos renderer.bc
[*] Running ikos preprocessor
[*] Running ikos analyzer
[!] ikos was compiled in debug mode, the analysis might be slow
[*] Translating LLVM bitcode to AR
ikos-analyzer: /var/folders/9g/hvg_xszs3q79k8tvtqhm_q5s5y3dxb/T/ikos-RKDGH_/renderer.pp.bc: error: unexpected llvm::BinaryOperator (opcode: fsub)
ikos: error: a run-time error occurred
```

This is tracked by #55

**Comment by ttsiodras** [comment]
(Back from vacation)

Confirmed - did a fresh build from 704adaee1bf180976657adb8a54aede3a915234a and reached the same bug. 

I also plan to try out ikos with the next mission codebase I analyse (I have performed more than 50 static analyses on mission codebases in the last 3 years - I work for ESA, btw). 

I will keep you posted (and also monitor the progress of the bug fixes here - looks like my renderer found a number of them).

**Comment by practicalswift** [comment]
@ttsiodras Very interesting! Which are your favourite static analysers (beyond IKOS!)? Sorry to hijack this issue: perhaps we can exchange static analyzer tips via e-mail? My e-mail is [github-name]@gmail.com :-)

**Comment by ttsiodras** [comment]
@practicalswift Good question. I plan to write a lengthy blog post about static analysis [on my site](https://www.thanassis.space/) - just as I did about [coverage](https://www.thanassis.space/coverage.html). SA is a very deep subject - sound vs unsound tools, integration into workflows, what are the expected benefits...  Writing a response in a GitHub comment wouldn't do it justice.

To be clear: I am walking a fine line, and obviously can't talk about specific products - only about things that you can expect from them (and what concrete results I've seen when I applied a number of tools to actual mission codebases). Internally in the Agency, I have given quite successful talks about the subject to my colleagues and to the Technical Officers that are leading the missions - and have recently begun to meet with NASA and JAXA people, exchanging more information on the subject. 

Will ping you guys when I post the article. It will take some time - currently drowning in work :-)

**Comment by practicalswift** [comment]
@ttsiodras Sounds very interesting! I understand that nothing employer specific can be said. I was mostly curious about your personal experiences - ideally using open source tools. More specifically what recommendations you would have for applying open source static analysis tools to a large C++ open source project such as Bitcoin Core (which I'm contributing to).

**Comment by ttsiodras** [comment]
@practicalswift  Not only "nothing employer specific" - in my position, I can't advocate for one tool or another. Regardless, I agree with [the recommendation that Gerard Holzmann gives](https://cacm.acm.org/magazines/2014/2/171689-mars-code/abstract) (just watch [that video](https://vimeo.com/84991949) if you can't read the paper, it's worth your time). It boils down to using as many analysers as you can - because what one misses, the other one finds.

If you can afford to, you then need to write your code in such a manner that it doesn't trigger false positives. If you can't afford to, and your code reviewer(s) (that is, not just you!) agree that a specific report is indeed a false positive, use the analyser's special comments to indicate it as such in the code.

I will elaborate about all these in the post, when I write it.

**Comment by ttsiodras** [comment]
Confirmed - analysis completed now.

Fixed!

**Comment by alcinos** [comment]
Sorry to reopen this, but I seem to be getting the same error:
```
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-leuyjyv4/kdenlive.pp.bc: error: unsupported dwarf encoding for llvm DIBasicType
ikos: error: a run-time error occurred
```

I'd be happy to share the bc file, but it's massive (52MB after zipping) so I can't attach it here.
