### ISSUE TITLE
Analyzing the same program using interval in ikos versus apron-interval, validating assertions with different results

### ISSUE THREAD

**Issue by hanxu202211** [NASA-SW-VnV/ikos#210]
int main(){
  int a=__ikos_nondet_int();
  int j;
  if (a) j=1;
  else j=2; 
  __ikos_assert(j==1 || j==2);
return 0;
}
The analysis using interval in ikos results in safe while  using apron-interval results in potentially unsafe.
I try to use the function __ikos_print_values("y",y) to print the value of y, and y is [1,2] using the interval in ikos,  the same as the apron-interval.

**Comment by arthaud** [comment]
This is probably a problem with APRON and not IKOS itself.
That assertion `j == 1 || j == 2` is translated into something like:
```
if (j == 1) {
  return true;
} else if (j == 2) {
  return true;
} else {
  return false;
}
```
This means we would take the current state, add the constraint `j != 1` and then `j != 2` and check if the state is empty.
My guess is that APRON does not correctly refine the interval to [2, 2] after adding the constraint `j != 1`.

**Comment by ivanperez-keera** [comment]
Following up on this. @hanxu202211 did you have a chance to try what @arthaud suggested?

**Comment by hanxu202211** [comment]
Yes, I tried Maxime's suggestion and verified that it was correct

**Comment by ivanperez-keera** [comment]
Great! I'm going to close this issue then. Please feel free to reopen of you think it's not really solved or something should be done.
