### ISSUE TITLE
Installation via Homebrew fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by bewagner** [NASA-SW-VnV/ikos#225]
When running 
```
brew install nasa-sw-vnv/core/ikos
```

I get the following error
```
Running `brew update --auto-update`...
==> Fetching nasa-sw-vnv/core/ikos
==> Downloading https://files.pythonhosted.org/packages/7e/ae/26808275fc76bf2832deb10d3a3ed3107bc4de01b85dcccbe525f2cd6d1e/Pygments-2.4.2.tar.gz
Already downloaded: /home/benjamin/.cache/Homebrew/downloads/6ca94f739e0ce8b61064d8fa84dcd6adf34e71e1a606f1ec9403a187965de88c--Pygments-2.4.2.tar.gz
==> Downloading https://github.com/NASA-SW-VnV/ikos/archive/refs/tags/v3.1.tar.gz
Already downloaded: /home/benjamin/.cache/Homebrew/downloads/e971bdc171d75200ec35ee75ce7b5309c06d0739a120ccada8501a84b52ee6d5--ikos-3.1.tar.gz
==> Installing ikos from nasa-sw-vnv/core
==> python3 -m venv --system-site-packages --without-pip /home/linuxbrew/.linuxbrew/Cellar/ikos/3.1_1/libexec/vendor
==> python3 -m pip --python=/home/linuxbrew/.linuxbrew/Cellar/ikos/3.1_1/libexec/vendor/bin/python install /tmp/ikos--Pygments-20230822-232482-lzr4i2/Pygments-2.4.2
==> cmake -G Unix Makefiles -DGMP_ROOT=/home/linuxbrew/.linuxbrew/opt/gmp -DMPFR_ROOT=/home/linuxbrew/.linuxbrew/opt/mpfr -DPPL_ROOT=/home/linuxbrew/.linuxbrew/opt/ppl -DAPRON_ROOT=/home/linuxbrew/.linuxbrew/opt/apron -DCUSTOM_BOOST_ROOT=/home/linuxbrew/.linuxbrew/opt/boost -DPYTHON_EXECUTABLE=/home/linuxbrew/.linuxbr
==> make install
Last 15 lines from /home/benjamin/.cache/Homebrew/Logs/ikos/04.make:
  890 |   if (m > n && match_prefix(p, q, n)) {
      |                                ^
/tmp/ikos-20230822-232482-1v67dyj/ikos-3.1/core/include/ikos/core/adt/patricia_tree/set.hpp:890:28: error: 'ikos::core::patricia_tree_utils::match_prefix' cannot be used as a function
  890 |   if (m > n && match_prefix(p, q, n)) {
      |                ~~~~~~~~~~~~^~~~~~~~~
/tmp/ikos-20230822-232482-1v67dyj/ikos-3.1/core/include/ikos/core/adt/patricia_tree/set.hpp:892:20: error: 'ikos::core::patricia_tree_utils::is_zero_bit' cannot be used as a function
  892 |     if (is_zero_bit(p, n)) {
      |         ~~~~~~~~~~~^~~~~~
make[2]: *** [ar/CMakeFiles/ikos-ar.dir/build.make:188: ar/CMakeFiles/ikos-ar.dir/src/pass/simplify_upcast_comparison.cpp.o] Error 1
make[2]: *** [ar/CMakeFiles/ikos-ar.dir/build.make:202: ar/CMakeFiles/ikos-ar.dir/src/semantic/bundle.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1497: ar/CMakeFiles/ikos-ar.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 16%] Linking CXX static library libikos-pp.a
[ 16%] Built target ikos-pp-lib
make: *** [Makefile:146: all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nasa-sw-vnv/homebrew-core/issues

These open issues may also help:
IKOS build fails on gcc12 https://github.com/NASA-SW-VnV/homebrew-core/issues/6
Unable to install IKOS 3.1 on Ubuntu 22.04 using Homebrew https://github.com/NASA-SW-VnV/homebrew-core/issues/7
Failed to install IKOS v3.1 with Homebrew on Ubuntu 20.04 (WSL-2) https://github.com/NASA-SW-VnV/homebrew-core/issues/5

```

How can I fix this?

**Comment by PhilipBotha** [comment]
Issue is that the tar.gz isn't updated with the latest version. So the data_layout.hpp header doesn't include the <vector> header.

**Comment by ivanperez-keera** [comment]
Thanks for reporting this. I'm looking into making a new release. I'll tag you when it's out.

**Comment by andrewkcorcoran** [comment]
Hi is there any workaround available for this? A previous version on homebrew for example?

**Comment by ivanperez-keera** [comment]
You can adjust the formula to use the latest version.

You can download a zip of the current master from: https://github.com/NASA-SW-VnV/ikos/archive/refs/heads/master.zip

AFAIK you'd only need to adjust the hash and the URL of the master file.

@maxmunzel, since you did it for #223, can you perhaps help @andrewkcorcoran adjust the formula to download the current master?

**Comment by maxmunzel** [comment]
@andrewkcorcoran as ivan said, run `brew edit nasa-sw-vnv/core/ikos`, change the url and the hash and try to `brew install` as usual. You may need to use the `tar.gz` archive however.

The relevant lines should be line right at the top (5 and 6).

**Comment by bewagner** [comment]
I just tried that, but it gives me 
![image](https://github.com/NASA-SW-VnV/ikos/assets/17410742/35834ccb-4281-42cc-ab81-7f0499a9221b)

**Comment by maxmunzel** [comment]
There seems to have been an update in brew. I fixed it by specifying some random version when I did my tinkering:

```ruby
class Ikos < Formula
  include Language::Python::Virtualenv
  desc "Static analyzer for C/C++ based on the theory of Abstract Interpretation"
  homepage "https://github.com/nasa-sw-vnv/ikos"
  url "http://demo.maxnagy.com:8000/get?q=qJ-ZqHFoThrGy3knp8p2XQ"
  sha256 "1017e7e4097f9b66f0431eaf85972ba57a3aa735e48d8c89510119a2f76b6fa1"
  license "MIT"
  revision 1
  version "2.542.1"
```

Does that work for you too?

**Comment by bewagner** [comment]
@maxmunzel No, sadly I still get
```
==> python3 -m venv --system-site-packages --without-pip /home/linuxbrew/.linuxbrew/Cellar/ikos/2.542.1_1/libexec/vendor
==> python3 -m pip --python=/home/linuxbrew/.linuxbrew/Cellar/ikos/2.542.1_1/libexec/vendor/bin/python install /tmp/ikos--Pygments-20231113-301225-16wzwkt/Pygments-2.4.2
==> cmake -G Unix Makefiles -DGMP_ROOT=/home/linuxbrew/.linuxbrew/opt/gmp -DMPFR_ROOT=/home/linuxbrew/.linuxbrew/opt/mpfr -DPPL_ROOT=/home/linuxbrew/.linuxbrew/opt/ppl -DAPRON_ROOT=/home/linuxbrew/.linuxbrew/opt/apron -DCUSTOM_BOOST_ROOT=/home/linuxbrew/.linuxbrew/opt/boost -DPYTHON_EXECUTABLE=/home/linuxbrew/.linuxbr
==> make install
Last 15 lines from /home/wab2rt/.cache/Homebrew/Logs/ikos/04.make:
  +++ |+#include <vector>
   52 | 
/tmp/ikos-20231113-301225-1s81wrb/ikos-3.1/ar/include/ikos/ar/semantic/data_layout.hpp:114:8: error: 'vector' in namespace 'std' does not name a template type
  114 |   std::vector< DataLayoutInfo > floats;
      |        ^~~~~~
/tmp/ikos-20231113-301225-1s81wrb/ikos-3.1/ar/include/ikos/ar/semantic/data_layout.hpp:114:3: note: 'std::vector' is defined in header '<vector>'; did you forget to '#include <vector>'?
  114 |   std::vector< DataLayoutInfo > floats;
      |   ^~~
make[2]: *** [ar/CMakeFiles/ikos-ar.dir/build.make:188: ar/CMakeFiles/ikos-ar.dir/src/pass/simplify_upcast_comparison.cpp.o] Error 1
make[2]: *** [ar/CMakeFiles/ikos-ar.dir/build.make:202: ar/CMakeFiles/ikos-ar.dir/src/semantic/bundle.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1528: ar/CMakeFiles/ikos-ar.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 16%] Linking CXX static library libikos-pp.a
[ 16%] Built target ikos-pp-lib
make: *** [Makefile:146: all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nasa-sw-vnv/homebrew-core/issues

These open issues may also help:
IKOS build fails on gcc12 https://github.com/NASA-SW-VnV/homebrew-core/issues/6
Unable to install IKOS 3.1 on Ubuntu 22.04 using Homebrew https://github.com/NASA-SW-VnV/homebrew-core/issues/7
Failed to install IKOS v3.1 with Homebrew on Ubuntu 20.04 (WSL-2) https://github.com/NASA-SW-VnV/homebrew-core/issues/5
```

**Comment by andrewkcorcoran** [comment]
> @andrewkcorcoran as ivan said, run `brew edit nasa-sw-vnv/core/ikos`, change the url and the hash and try to `brew install` as usual. You may need to use the `tar.gz` archive however.
> 
> The relevant lines should be line right at the top (5 and 6).

hmm is there a way to set this up programmatically, e.g. applying a diff or similar? The reason I ask is that we need to install IKOS into a docker container so it needs to be setup to be done without manual intervention.

**Comment by maxmunzel** [comment]
That's possible, but probably outside the scope of ikos. The brew formulas are just some git repos on your pc. `brew edit` also tells you the location of the formula (if not, try `EDITOR=ls brew edit ikos`. You can just overwrite the formula within your docker file. The other option is to fork https://github.com/NASA-SW-VnV/homebrew-core and use it as its own tap.

**Comment by ivanperez-keera** [comment]
Until we publish the new version (again, should happen hopefully in weeks), you can also install without brew.

Since you are using docker I'm assuming your guest is linux. We have a sample dockerfile here: https://github.com/NASA-SW-VnV/ikos/issues/171#issuecomment-1625968905.

We also have Github Actions scripts, which may serve as precise documentation to build ikos: https://github.com/NASA-SW-VnV/ikos/tree/master/.github/workflows.

**Comment by ivanperez-keera** [comment]
Just keeping you up to date: I'm now trying to close the release. This and https://github.com/NASA-SW-VnV/ikos/discussions/241 will be the last things I plan to deal with.

**Comment by ivanperez-keera** [comment]
Update: The last change due for inclusion in IKOS 3.2 has been completed. We'll publish a release candidate and fix this issue in the brew formulas. I'll ping you when it's ready to try.

**Comment by ivanperez-keera** [comment]
I have forked the brew formulas repo and adjusted IKOS's formula to point to the new release candidate, IKOS 3.2-rc1.

You should be able to try it with:
```sh
$ brew install ivanperez-keera/homebrew/ikos
```

For completion, here's a dockerfile that worked for me. Note that it uses jammy, not focal as your issue mentioned, because llvm14 is not available in the focal repositories (Ubuntu 20.04). There may be a way to install it llvm14 in focal, but I have not investigated. I also have not tried to optimize the packages installed; I would not be surprised if this image could be made smaller:

```Dockerfile
FROM ubuntu:jammy
MAINTAINER Ivan Perez <ivan.perezdominguez@nasa.gov>
ENV DEBIAN_FRONTEND=noninteractive                                               

# Update package DB
RUN apt-get update

# Install all dependencies
RUN apt-get install --yes gcc g++ cmake libgmp-dev libboost-dev libboost-filesystem-dev \
    libboost-thread-dev libboost-test-dev python3 libsqlite3-dev libtbb-dev \
    libz-dev libedit-dev llvm-14 llvm-14-dev llvm-14-tools clang-14 \
    git pip curl

# Install brew
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
RUN (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /root/.bashrc

# Install ikos
RUN eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && brew install ivanperez-keera/homebrew-core/ikos
```

After downloading that file, it can be built with:
```sh
$ docker build -t ikos:3.2-rc1 -f <path_to_dockerfile> .
```

And then one should be able to just run IKOS inside docker with:
```sh
$ docker run -it ikos:3.2-rc1
root@<some_container_id>:/# ikos --version
ikos 3.2-rc1
Copyright (c) 2011-2023 United States Government as represented by the
Administrator of the National Aeronautics and Space Administration.
All Rights Reserved.
```

Please let me know how it goes and if that will solve your issue.

**Comment by ivanperez-keera** [comment]
Gentle nudge @bewagner . Please let me know if the new formula fixes your issue.

IKOS 3.2 will be released soon.

**Comment by bewagner** [comment]
Thanks @ivanperez-keera, I tried the formula last week and was able to install 🎉

**Comment by ivanperez-keera** [comment]
Awesome! Thank you so much for getting back to me so quickly.

I'll close this issue when 3.2 is officially released and the new formula merged. It'll be just one more day or so.

**Comment by ivanperez-keera** [comment]
IKOS 3.2 is now released and the homebrew formula has been updated. Please open a new issue if you have trouble installing it. Thanks!
