### ISSUE TITLE
Is there any documents about AR?

### ISSUE THREAD

**Issue by zoush99** [NASA-SW-VnV/ikos#226]
Hi, everyone! do you have some syntactic details, or documentation, about your own design of the abstract representation language (AR)? When I read the source code, I find that there is a lot designed in it and it is not intuitive enough. Thank you guys! Thank you for doing the work for the program analysis and open-sourcing the results so that I have the opportunity to learn from it!

**Comment by arthaud** [comment]
Unfortunately, AR is pretty loosely documented.
In a way, it is pretty similar to the LLVM language: https://llvm.org/docs/LangRef.html
Each instruction is pretty much translated 1:1 into AR.
You can find the implementation of the translation in https://github.com/NASA-SW-VnV/ikos/blob/master/frontend/llvm/src/import/function.cpp#L305
The major differences are:
* AR integer types are either signed or unsigned.  LLVM integers do not have a signedness.
* AR has a concept of local variables. LLVM has a[ `alloca` instruction](https://llvm.org/docs/LangRef.html#alloca-instruction) that allocates memory on the stack (effectively a local variable).
* AR has names for variables, LLVM doesn't (names are in the debugging information, which is stored in a different format)

**Comment by zoush99** [comment]
Oh, thank you very much for getting back to me so quickly. I intend to use your IKOS to support defect detection of Fortran programs, so I need to modify the work of LLVM2AR and make extensions to the feature section for different C++ programs, to make a demonstration of how IKOS can support more high-level language analysis afterwards.
