### ISSUE TITLE
Link error on debian 9

### ISSUE THREAD

**Issue by arthaud** [NASA-SW-VnV/ikos#23]
I tried IKOS on Debian 9 two days ago and it worked perfectly.
I tried again today, and I'm getting a linker error.
I will investigate whenever I have time.

```
root@f67f01e4d08f:~/ikos/build# make all check
Scanning dependencies of target ikos-ar
[  0%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/format/dot.cpp.o
[  1%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/format/namer.cpp.o
[  1%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/format/text.cpp.o
[  3%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/add_loop_counters.cpp.o
[  3%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/name_values.cpp.o
[  4%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/pass.cpp.o
[  4%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/simplify_cfg.cpp.o
[  6%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/unify_exit_nodes.cpp.o
[  6%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/simplify_upcast_comparison.cpp.o
[  8%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/bundle.cpp.o
[  8%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/code.cpp.o
[  9%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/context.cpp.o
[  9%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/context_impl.cpp.o
[ 11%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/data_layout.cpp.o
[ 12%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/function.cpp.o
[ 12%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/intrinsic.cpp.o
[ 14%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/statement.cpp.o
[ 14%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/type.cpp.o
[ 16%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/value.cpp.o
[ 16%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/verify/frontend.cpp.o
[ 17%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/verify/type.cpp.o
[ 17%] Linking CXX static library libikos-ar.a
[ 17%] Built target ikos-ar
Scanning dependencies of target ikos-llvm-to-ar
[ 19%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/bundle.cpp.o
[ 19%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/constant.cpp.o
[ 20%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/data_layout.cpp.o
[ 20%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/exception.cpp.o
[ 22%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/function.cpp.o
[ 22%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/importer.cpp.o
[ 24%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/library_function.cpp.o
[ 25%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/source_location.cpp.o
[ 25%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/type.cpp.o
[ 27%] Linking CXX static library libikos-llvm-to-ar.a
[ 27%] Built target ikos-llvm-to-ar
Scanning dependencies of target ikos-pp-lib
[ 27%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/initialize.cpp.o
[ 29%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/lower_cst_expr.cpp.o
[ 29%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/lower_select.cpp.o
[ 30%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/mark_internal_inline.cpp.o
[ 30%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/mark_no_return_function.cpp.o
[ 32%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/name_values.cpp.o
[ 32%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/remove_printf_calls.cpp.o
[ 33%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/remove_unreachable_blocks.cpp.o
[ 33%] Linking CXX static library libikos-pp.a
[ 33%] Built target ikos-pp-lib
Scanning dependencies of target ikos-pp
[ 33%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o
[ 35%] Linking CXX executable ikos-pp
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMBitWriter.a(BitcodeWriterPass.cpp.o): SHT_GROUP section [index 24] has no SHF_GROUP sections
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMBitWriter.a(BitcodeWriterPass.cpp.o): SHT_GROUP section [index 25] has no SHF_GROUP sections
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMBitWriter.a(BitcodeWriterPass.cpp.o): SHT_GROUP section [index 26] has no SHF_GROUP sections
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMBitWriter.a(BitcodeWriterPass.cpp.o): SHT_GROUP section [index 24] has no SHF_GROUP sections
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMBitWriter.a(BitcodeWriterPass.cpp.o): SHT_GROUP section [index 25] has no SHF_GROUP sections
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMBitWriter.a(BitcodeWriterPass.cpp.o): SHT_GROUP section [index 26] has no SHF_GROUP sections
/usr/lib/llvm-7/lib/libLLVMBitWriter.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
frontend/llvm/CMakeFiles/ikos-pp.dir/build.make:134: recipe for target 'frontend/llvm/ikos-pp' failed
make[2]: *** [frontend/llvm/ikos-pp] Error 1
CMakeFiles/Makefile2:1547: recipe for target 'frontend/llvm/CMakeFiles/ikos-pp.dir/all' failed
make[1]: *** [frontend/llvm/CMakeFiles/ikos-pp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by arthaud** [comment]
It looks like there is something wrong with the `llvm-7-dev` package.
I opened an issue: https://bugs.llvm.org/show_bug.cgi?id=40059

**Comment by CarysT** [comment]
This is a problem I am also getting on gentoo with GCC 8.2.0 & LLVM 7.0.

`carys@caryspc ~/Desktop/work/ikos/build $ REQUIRES_RTTI=1 make -j13
Scanning dependencies of target ikos-python
Scanning dependencies of target ikos-pp-lib
Scanning dependencies of target ikos-llvm-to-ar
Scanning dependencies of target ikos-ar
[  0%] Generating python/ikos/settings/__init__.py
[  1%] Generating python/build/lib/ikos/__init__.py
[  1%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/format/dot.cpp.o
[  1%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/name_values.cpp.o
[  3%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/format/namer.cpp.o
[  3%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/format/text.cpp.o
[  4%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/add_loop_counters.cpp.o
[  6%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/pass.cpp.o
[  6%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/simplify_upcast_comparison.cpp.o
[  8%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/bundle.cpp.o
[  8%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/simplify_cfg.cpp.o
[  9%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/pass/unify_exit_nodes.cpp.o
[ 11%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/code.cpp.o
[ 11%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/context.cpp.o
[  9%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/context_impl.cpp.o
[ 12%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/data_layout.cpp.o
[ 14%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/intrinsic.cpp.o
[ 14%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/function.cpp.o
[ 16%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/statement.cpp.o
[ 16%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/initialize.cpp.o
[ 16%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/type.cpp.o
[ 17%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/bundle.cpp.o
[ 19%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/semantic/value.cpp.o
[ 20%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/lower_cst_expr.cpp.o
[ 20%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/constant.cpp.o
[ 22%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/data_layout.cpp.o
[ 24%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/mark_internal_inline.cpp.o
[ 25%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/verify/type.cpp.o
[ 20%] Building CXX object ar/CMakeFiles/ikos-ar.dir/src/verify/frontend.cpp.o
[ 25%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/exception.cpp.o
[ 25%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/lower_select.cpp.o
[ 25%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/mark_no_return_function.cpp.o
[ 27%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/name_values.cpp.o
[ 29%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/function.cpp.o
[ 29%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/remove_printf_calls.cpp.o
[ 30%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp-lib.dir/src/pass/remove_unreachable_blocks.cpp.o
[ 30%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/importer.cpp.o
[ 32%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/library_function.cpp.o
[ 33%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/source_location.cpp.o
[ 33%] Built target ikos-python
[ 33%] Building CXX object frontend/llvm/CMakeFiles/ikos-llvm-to-ar.dir/src/import/type.cpp.o
[ 33%] Linking CXX static library libikos-ar.a
[ 33%] Linking CXX static library libikos-pp.a
[ 35%] Linking CXX static library libikos-llvm-to-ar.a
[ 35%] Built target ikos-ar
[ 35%] Built target ikos-pp-lib
Scanning dependencies of target ikos-pp
[ 35%] Built target ikos-llvm-to-ar
Scanning dependencies of target ikos-import
Scanning dependencies of target ikos-analyzer
[ 35%] Building CXX object frontend/llvm/CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o
[ 37%] Building CXX object frontend/llvm/CMakeFiles/ikos-import.dir/src/ikos_import.cpp.o
[ 38%] Linking CXX executable ikos-pp
[ 38%] Linking CXX executable ikos-import
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o: undefined reference to symbol '_ZN4llvm31initializeAggressiveInstCombineERNS_12PassRegistryE'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/llvm/7/lib64/libLLVMAggressiveInstCombine.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [frontend/llvm/CMakeFiles/ikos-pp.dir/build.make:105: frontend/llvm/ikos-pp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1618: frontend/llvm/CMakeFiles/ikos-pp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: libikos-llvm-to-ar.a(data_layout.cpp.o): undefined reference to symbol '_ZN4llvm11IntegerType3getERNS_11LLVMContextEj'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/llvm/7/lib64/libLLVMCore.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [frontend/llvm/CMakeFiles/ikos-import.dir/build.make:91: frontend/llvm/ikos-import] Error 1
make[1]: *** [CMakeFiles/Makefile2:1693: frontend/llvm/CMakeFiles/ikos-import.dir/all] Error 2
[ 38%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/ikos_analyzer.cpp.o
[ 38%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/fixpoint_profile.cpp.o
[ 38%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/literal.cpp.o
[ 41%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/call_context.cpp.o
[ 41%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/hardware_addresses.cpp.o
[ 43%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/liveness.cpp.o
[ 43%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/memory_location.cpp.o
[ 45%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/option.cpp.o
[ 45%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/pointer/constraint.cpp.o
[ 46%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/pointer/function.cpp.o
[ 46%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/pointer/pointer.cpp.o
[ 48%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/pointer/value.cpp.o
[ 48%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/interprocedural.cpp.o
[ 50%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/intraprocedural.cpp.o
[ 50%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/apron_interval.cpp.o
[ 51%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/apron_octagon.cpp.o
[ 53%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/apron_pkgrid_polyhedra_lin_cong.cpp.o
[ 53%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/apron_polka_linear_equalities.cpp.o
[ 54%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/apron_polka_polyhedra.cpp.o
[ 54%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/apron_ppl_linear_congruences.cpp.o
[ 56%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/apron_ppl_polyhedra.cpp.o
[ 56%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/congruence.cpp.o
[ 58%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/dbm.cpp.o
[ 59%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/gauge_interval_congruence.cpp.o
[ 59%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/gauge.cpp.o
[ 61%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/interval_congruence.cpp.o
[ 61%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/interval.cpp.o
[ 61%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_apron_octagon.cpp.o
[ 62%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_apron_pkgrid_polyhedra_lin_cong.cpp.o
[ 62%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_apron_polka_linear_equalities.cpp.o
[ 64%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_apron_polka_polyhedra.cpp.o
[ 64%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_apron_ppl_linear_congruences.cpp.o
[ 66%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_apron_ppl_polyhedra.cpp.o
[ 66%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_dbm.cpp.o
[ 67%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/value/machine_int_domain/var_pack_dbm_congruence.cpp.o
[ 69%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/analysis/variable.cpp.o
[ 69%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/assert_prover.cpp.o
[ 70%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/buffer_overflow.cpp.o
[ 72%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/dead_code.cpp.o
[ 72%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/division_by_zero.cpp.o
[ 72%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/checker.cpp.o
[ 72%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/function_call.cpp.o
[ 74%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/double_free.cpp.o
[ 75%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/int_overflow_base.cpp.o
[ 75%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/null_dereference.cpp.o
[ 77%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/pointer_alignment.cpp.o
[ 77%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/pointer_compare.cpp.o
[ 79%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/pointer_overflow.cpp.o
[ 79%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/shift_count.cpp.o
[ 80%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/signed_int_overflow.cpp.o
[ 80%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/soundness.cpp.o
[ 82%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/uninitialized_variable.cpp.o
[ 82%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/output.cpp.o
[ 83%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/checker/unsigned_int_overflow.cpp.o
[ 85%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/sqlite.cpp.o
[ 85%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table.cpp.o
[ 87%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/call_contexts.cpp.o
[ 87%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/checks.cpp.o
[ 88%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/files.cpp.o
[ 88%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/functions.cpp.o
[ 90%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/memory_locations.cpp.o
[ 90%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/operands.cpp.o
[ 91%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/settings.cpp.o
[ 91%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/statements.cpp.o
[ 93%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/database/table/times.cpp.o
[ 93%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/exception.cpp.o
[ 95%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/json/json.cpp.o
[ 95%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/util/color.cpp.o
[ 96%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/util/log.cpp.o
[ 96%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/util/timer.cpp.o
[ 98%] Building CXX object analyzer/CMakeFiles/ikos-analyzer.dir/src/util/source_location.cpp.o
[100%] Linking CXX executable ikos-analyzer
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../frontend/llvm/libikos-llvm-to-ar.a(data_layout.cpp.o): undefined reference to symbol '_ZN4llvm11IntegerType3getERNS_11LLVMContextEj'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/llvm/7/lib64/libLLVMCore.so.7: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [analyzer/CMakeFiles/ikos-analyzer.dir/build.make:1144: analyzer/ikos-analyzer] Error 1
make[1]: *** [CMakeFiles/Makefile2:1827: analyzer/CMakeFiles/ikos-analyzer.dir/all] Error 2
make: *** [Makefile:141: all] Error 2`

**Comment by arthaud** [comment]
Hi @CarysT,

Thanks for reporting it.

Since this is a different error on a different operating system, please open a separate issue.

**Comment by CarysT** [comment]
Sorry, It looked like the same issue. I will resubmit it.

**Comment by arthaud** [comment]
This has been fixed.
