### ISSUE TITLE
brew install nasa-sw-vnv/core/ikos fails at Apron patch

### ISSUE THREAD

**Issue by andrewkcorcoran** [NASA-SW-VnV/ikos#237]
```bash
==> Installing nasa-sw-vnv/core/ikos dependency: nasa-sw-vnv/core/apron
==> Patching
Error: Failure while executing; `patch -g 0 -f -p0` exited with 127. Here's the output:
```

**Comment by ivanperez-keera** [comment]
Hi @andrewkcorcoran . Thanks for filing this.

Could you provide a bit more information about this? Can you run it with `-v` perhaps (or even `-d`)?

I don't expect patches can easily fail: it's pulling a known version of apron and checking the hashsum.

If it's applying one of these patches, I'd like to know which one specifically is failing:

https://github.com/NASA-SW-VnV/homebrew-core/blob/24cbcc2dfc254f27e2ffcebd56f6f670c709b05b/Formula/apron.rb#L12-L74

**Comment by andrewkcorcoran** [comment]
Seems patch wasn't installed on the host...

**Comment by andrewkcorcoran** [comment]
Just a though - does this imply that ikos is missing a dependency on patch in its brew definition?

**Comment by ivanperez-keera** [comment]
I think you are absolutely right. The ikos formula must be missing a dependency on "patch".

If you know how to modify it and install from your version, you can uninstall "patch" and try it.

**Comment by ivanperez-keera** [comment]
It that solves the issue, then the problem should be filed agains: https://github.com/NASA-SW-VnV/homebrew-core/
