### ISSUE TITLE
Forward -I and -D flags to clang

### ISSUE THREAD

**Issue by arthaud** [NASA-SW-VnV/ikos#24]
This was requested a lot on reddit, and I think this is a good idea.

Feel free to suggest other flags.

**Comment by kokke** [comment]
Good ideas. I also suggest -m to be able to control whether we're building for a 32 or 64 bit architecture.

**Comment by arthaud** [comment]
@kokke: I will add `-m` too.

By the way, I'm still trying to write a report about the influence of IKOS in the industry.
@kokke, your input would be really appreciated ;)
