### ISSUE TITLE
add CMake support

### ISSUE THREAD

**Issue by J-Roux** [NASA-SW-VnV/ikos#25]
I can't check my project on CMake even using Makefile as a generator.

**Comment by alex-justes** [comment]
Small update:
Actually it works. At least on simple cmake projects. Though it fails on my company's project (so i can't share it), but i'll try to figure out why it fails in my free time.

**Comment by arthaud** [comment]
Hi @J-Roux and @alex-justes,

`ikos-scan` supports `cmake`.
It should be used with `ikos-scan cmake [parameters] ..` and `ikos-scan make`.
Do not try to use `-DCMAKE_C_COMPILER` and `-DCMAKE_CXX_COMPILER`, it won't work.

If you get errors, please try with `ikos-scan -vvv make` and post the logs here, thanks.
If you have an example (e.g, on github) to reproduce the issue, this would be even more helpful.

**Comment by alex-justes** [comment]
I've found, what have caused compilation problems: it was -flto flag in one of the sub directories in the project (release configuration was selected by default and that flag caused broken *.o files (llvm-obj-routines couldn't recognize it), by the way release configuration works without -flto).

Debug configuration also works :)

**Comment by arthaud** [comment]
@alex-justes: Good to hear!
@J-Roux: If you still have issues, see my previous comment.

I will close this in a few days if I don't get any news.
