### ISSUE TITLE
error: unexpected negative count for llvm::DICompositeType with DW_TAG_array_type tag

### ISSUE THREAD

**Issue by victorjulien** [NASA-SW-VnV/ikos#26]
When trying out Ikos on the Suricata code base, I see the following error:
<pre>
root@c08dee9a79a9:~/suricata# ikos -v src/suricata.bc 
[*] Running ikos preprocessor
[.] Running /ikos/install/bin/ikos-pp -opt=basic -entry-points=main src/suricata.bc -o /tmp/ikos-r7ALl_/suricata.pp.bc
[*] Running ikos analyzer
[.] Running /ikos/install/bin/ikos-analyzer -a=sound,shc,nullity,pcmp,dfa,dca,fca,prover,dbz,boa,sio -d=interval -entry-points=main -globals-init=skip-big-arrays -prec=mem -proc=inter -allow-dbg-mismatch -display-checks=no -display-inv=no -color=auto -log=debug /tmp/ikos-r7ALl_/suricata.pp.bc -o output.db
[.] Creating output database output.db
[.] Loading LLVM bitcode
[.] Verifying integrity of LLVM bitcode
[.] Checking for debug information
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-r7ALl_/suricata.pp.bc: error: unexpected negative count for llvm::DICompositeType with DW_TAG_array_type tag
ikos: error: a run-time error occured
</pre>

The error looks a lot like the one in #18. The suggested work around there doesn't work, since -allow-dbg-mismatch is already passed to ikos-analyzer.

This is on Ubuntu 18.10 in a docker setup.

**Comment by practicalswift** [comment]
FWIW I've hit this issue when running IKOS against the [C-Lightning project](https://github.com/ElementsProject/lightning).

Let me know if I can help by providing any details.

**Comment by arthaud** [comment]
I just fixed a similar issue: #47 

Could you please try again with the most recent changes of ikos?

**Comment by practicalswift** [comment]
@arthaud Confirming that deb022172601d55e81842426c0fa9bea85314fb6 seems to have fixed the problem I encountered. Thanks for the impressive turnaround time and an excellent tool!

**Comment by arthaud** [comment]
Good to hear.
Thanks!

**Comment by victorjulien** [comment]
Fixed for me as well, thanks!
