### ISSUE TITLE
could not install ikos for ubuntu 20.04

### ISSUE THREAD

**Issue by aogrcs** [NASA-SW-VnV/ikos#271]
I have tried many times to install ikos for ubuntu 20.04, but It does not success, there are some errors:

==> Fetching nasa-sw-vnv/core/apron
==> Downloading http://apron.cri.ensmp.fr/library/apron-0.9.10.tgz
Already downloaded: /home/cocosim/.cache/Homebrew/downloads/34a965edee1371d94da025a09ba608766ae7a3afc1c878e2a1a0053d2fb822d8--apron-0.9.10.tgz
==> Installing apron from nasa-sw-vnv/core
==> Patching
==> make APRON_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/apron/0.9.10_1 GMP_PREFIX=/home/linuxbrew/.linuxbrew/opt/gmp MPFR_PREFIX=/home/linuxbrew/.linuxbrew/opt/mpfr PPL_PREFIX=/home/linuxbrew/.linuxbrew/
Last 15 lines from /home/cocosim/.cache/Homebrew/Logs/apron/01.make:
  591 |                                                   &pk_meet_lincons_array);
      |                                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   pk_t * (*)(ap_manager_t *, bool,  pk_t *, ap_lincons0_array_t *) {aka pk_t * (*)(ap_manager_t *, char,  pk_t *, ap_lincons0_array_t *)}
In file included from pk_meetjoin.c:20:
../apron/ap_generic.h:87:50: note: expected 'void * (*)(ap_manager_t *, bool,  void *, ap_lincons0_array_t *)' {aka 'void * (*)(ap_manager_t *, char,  void *, ap_lincons0_array_t *)'} but argument is of type 'pk_t * (*)(ap_manager_t *, bool,  pk_t *, ap_lincons0_array_t *)' {aka 'pk_t * (*)(ap_manager_t *, char,  pk_t *, ap_lincons0_array_t *)'}
   87 |                                          void* (*meet_lincons_array)(ap_manager_t*,
      |                                          ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   88 |                                                                      bool, void*,
      |                                                                      ~~~~~~~~~~~~
   89 |                                                                      ap_lincons0_array_t*));
      |                                                                      ~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:204: pk_meetjoinMPQ.o] Error 1
make[1]: Leaving directory '/tmp/apron-20240522-30176-bo66gs/apron-0.9.10/newpolka'
make: *** [Makefile:22: c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/nasa-sw-vnv/homebrew-core/issues

These open issues may also help:
Apron `incompatible function pointer type` error on Intel Mac https://github.com/NASA-SW-VnV/homebrew-core/issues/17

or install ikos 3.3:

/usr/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
/usr/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyIbEE[_ZTIN4llvm2cl15OptionValueCopyIbEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
/usr/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o:(.data.rel.ro._ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE[_ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE]+0x18): undefined reference to `typeinfo for llvm::cl::Option'
/usr/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyI12OptLevelTypeEE[_ZTIN4llvm2cl15OptionValueCopyI12OptLevelTypeEE]+0x10): undefined reference to `typeinfo for llvm::cl::GenericOptionValue'
/usr/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o:(.data.rel.ro._ZTIN4llvm2cl6parserI12OptLevelTypeEE[_ZTIN4llvm2cl6parserI12OptLevelTypeEE]+0x10): undefined reference to `typeinfo for llvm::cl::generic_parser_base'
/usr/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o:(.data.rel.ro._ZTIN4llvm2cl3optI12OptLevelTypeLb0ENS0_6parserIS2_EEEE[_ZTIN4llvm2cl3optI12OptLevelTypeLb0ENS0_6parserIS2_EEEE]+0x18): undefined reference to `typeinfo for llvm::cl::Option'
/usr/bin/ld: CMakeFiles/ikos-pp.dir/src/ikos_pp.cpp.o:(.data.rel.ro._ZTIN4llvm2cl4listIPKNS_8PassInfoEbNS_14PassNameParserEEE[_ZTIN4llvm2cl4listIPKNS_8PassInfoEbNS_14PassNameParserEEE]+0x18): undefined reference to `typeinfo for llvm::cl::Option'
/usr/bin/ld: libikos-pp.a(lower_cst_expr.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_116LowerCstExprPassE+0x10): undefined reference to `typeinfo for llvm::FunctionPass'
/usr/bin/ld: libikos-pp.a(lower_select.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_115LowerSelectPassE+0x10): undefined reference to `typeinfo for llvm::FunctionPass'
/usr/bin/ld: libikos-pp.a(name_values.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_114NameValuesPassE+0x10): undefined reference to `typeinfo for llvm::ModulePass'
/usr/bin/ld: libikos-pp.a(remove_printf_calls.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_121RemovePrintfCallsPassE+0x10): undefined reference to `typeinfo for llvm::FunctionPass'
/usr/bin/ld: libikos-pp.a(mark_internal_inline.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_122MarkInternalInlinePassE+0x10): undefined reference to `typeinfo for llvm::ModulePass'
/usr/bin/ld: libikos-pp.a(remove_unreachable_blocks.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_127RemoveUnreachableBlocksPassE+0x10): undefined reference to `typeinfo for llvm::FunctionPass'
collect2: error: ld returned 1 exit status
make[2]: *** [frontend/llvm/CMakeFiles/ikos-pp.dir/build.make:143: frontend/llvm/ikos-pp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1568: frontend/llvm/CMakeFiles/ikos-pp.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Could anyone give me some help, thanks

**Comment by ivanperez-keera** [comment]
I'm looking into this right now. There's been new releases of Apron, which I'm trying.

**Comment by ivanperez-keera** [comment]
It seems to be a problem with Apron. I'm opened an issue here: https://github.com/antoinemine/apron/issues/118

**Comment by ivanperez-keera** [comment]
This appears to be working now. A new release of Apron fixed those issues. Please try again and let me know if it still does not work. Thanks!
