### ISSUE TITLE
new release of ikos for space-ros

### ISSUE THREAD

**Issue by asimonov** [NASA-SW-VnV/ikos#280]
now that #273 is fixed, can we have a new release to use in space-ros Jazzy upgrade please?

**Comment by ivanperez-keera** [comment]
I'm planning to make a new release, yes. (It won't be tied to this issue, so I'll those this for now.)

**Comment by asimonov** [comment]
ok. i created an issue to track it easier among space-ros jazzy upgrade tasks

**Comment by ivanperez-keera** [comment]
I've made a new release of IKOS now. You should be able to pin ikos 3.4.

**Comment by asimonov** [comment]
> I've made a new release of IKOS now. You should be able to pin ikos 3.4.

lovely! thanks @ivanperez-keera!
