### ISSUE TITLE
Problem to run IKOS in macOS sequoia 15.1

### ISSUE THREAD

**Issue by AlPeUAG** [NASA-SW-VnV/ikos#297]
I install IKOS using the brew command, then when I try to analyze any code, this error appears: error could not find ikos python module, error: see TROUBLESHOOTING.md
What could be wrong, I already reinstall ikos with brew but is the same, someone can help me?

**Comment by drpaneas** [comment]
Same here.

**Comment by fouzhe** [comment]
Same here

**Comment by TheBjoel2** [comment]
https://github.com/jupyter/nbclassic/issues/308

**Comment by ivanperez-keera** [comment]
It could be a duplicate of #292. Could you try the latest version in the repo (not yet tagged) and see if that works?

**Comment by ivanperez-keera** [comment]
A similar issue was reported (https://github.com/NASA-SW-VnV/ikos/issues/305) and was fixed when #292 was fixed. Reinstalling from source until the next release should address the issue.

If not, please re-open this ticket. Thanks!
