### ISSUE TITLE
ikos-view produces line numbers that are off by one

### ISSUE THREAD

**Issue by gh2375** [NASA-SW-VnV/ikos#32]
ikos-view produces an output that is off by one line when the file starts with an empty line. Please note that this is independent of https://github.com/NASA-SW-VnV/ikos/issues/12 as this issue occurs both with Windows (CR LF) as well as Unix (LF) line endings.

### Minimal working example:
```

#include <vector>

int main(int argc, char * argv[])
{
    std::vector<int> v;

    v.resize(10);

    for(int * p = v.data(); p < v.data() + 10; p++)
        if(*p == 0)
            return 1;

    return 0;
}
```

### Output:
With first line empty:
![off-by-one](https://user-images.githubusercontent.com/45862319/49975131-728c9c00-ff34-11e8-8b54-4f83095d841e.png)

With empty line removed:
![correct](https://user-images.githubusercontent.com/45862319/49975122-656fad00-ff34-11e8-98d5-cd45f6787e48.png)

### System:
MSYS2

### Version:
```
$ ./ikos --version
ikos 2.1
```

**Comment by arthaud** [comment]
Hi @gh2375, thank you for the bug report.
It was actually a problem in ikos-view and pygments.
