### ISSUE TITLE
ikos: error while preprocessing llvm bitcode, abort.

### ISSUE THREAD

**Issue by minamonk** [NASA-SW-VnV/ikos#4]
Good day,

I managed to run ikos properly and compile a test program.
running "extract-bc" works as advertised and produces a *.bc bytecode file.
then when I run:
`ikos cli.bc`

I get this:
`[*] Running ikos preprocessor
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
We only lower a select if the flag is Boolean.
Branch condition is not 'i1' type!
  br <4 x i1> %1407, label %1409, label %1410
  %1407 = and <4 x i1> %1406, %1405
Branch condition is not 'i1' type!
  br <4 x i1> %1421, label %1423, label %1424
  %1421 = and <4 x i1> %1420, %1419
Branch condition is not 'i1' type!
  br <4 x i1> %1435, label %1437, label %1438
  %1435 = and <4 x i1> %1434, %1433
Branch condition is not 'i1' type!
  br <4 x i1> %1449, label %1451, label %1452
  %1449 = and <4 x i1> %1448, %1447
Branch condition is not 'i1' type!
  br <4 x i1> %1463, label %1465, label %1466
  %1463 = and <4 x i1> %1462, %1461
Branch condition is not 'i1' type!
  br <4 x i1> %1477, label %1479, label %1480
  %1477 = and <4 x i1> %1476, %1475
Branch condition is not 'i1' type!
  br <4 x i1> %1491, label %1493, label %1494
  %1491 = and <4 x i1> %1490, %1489
Branch condition is not 'i1' type!
  br <4 x i1> %1505, label %1507, label %1508
  %1505 = and <4 x i1> %1504, %1503
Branch condition is not 'i1' type!
  br <4 x i1> %1519, label %1521, label %1522
  %1519 = and <4 x i1> %1518, %1517
Branch condition is not 'i1' type!
  br <4 x i1> %1533, label %1535, label %1536
  %1533 = and <4 x i1> %1532, %1531
Branch condition is not 'i1' type!
  br <4 x i1> %1547, label %1549, label %1550
  %1547 = and <4 x i1> %1546, %1545
Branch condition is not 'i1' type!
  br <4 x i1> %1561, label %1563, label %1564
  %1561 = and <4 x i1> %1560, %1559
LLVM ERROR: Broken function found, compilation aborted!
ikos: error while preprocessing llvm bitcode, abort.
`

`clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm@4/bin`

It appears that LLVM has a broken function somewhere and other projects not Ikos related have had the same issue based on my Google results. Have any of you come across this while using Ikos and how was it solved?

**Comment by arthaud** [comment]
Hi @minamonk,

The problem comes from the lower-select llvm pass, see https://github.com/NASA-SW-VnV/ikos/blob/master/frontend/llvm/src/pass/lower_select.cpp#L62

Try to compile everything in debug mode and without optimization (-g -O0). That might solve the problem. This is something I should have mentioned in the documentation.

**Comment by arthaud** [comment]
Any news about this issue?

**Comment by arthaud** [comment]
I am closing this since it looks like it was fixed.
