### ISSUE TITLE
error: unexpected ar::Type in add_bitcast()

### ISSUE THREAD

**Issue by practicalswift** [NASA-SW-VnV/ikos#43]
```
$ cat testcase.c
#include <stdint.h>
struct a {
  signed b : 5;
  int32_t c;
  signed d
};
e;
struct a f(uint16_t, *, *);
g() {
  int32_t h;
  i(f(i, e, h));
}
struct a f(uint16_t j, *k, *l) {}
$ ikos testcase.c 2>&1 | tail -2
ikos-analyzer: …: error: unexpected ar::Type in add_bitcast()
ikos: error: a run-time error occured
```

**Comment by arthaud** [comment]
I improved the type inference in the translation from llvm to ar.

Using d61480adb9d4185fc744b1a6e01cb7badc47641e fixes the given example, but we will probably have more issues with `add_bitcast()`. I'm letting this issue closed but please open a new issue if you find the same error with a different example, thanks.

**Comment by practicalswift** [comment]
Confirming that I'm no longer hitting this issue.
