### ISSUE TITLE
Problem with widening global pointers in loop

### ISSUE THREAD

**Issue by wutianba** [NASA-SW-VnV/ikos#6]
```c++
int *p;
void main() {
  int i;
  int A[4];
  p = A;
  for (i = 0; i < 10; i++) {
    p++;  
  }
}
```
if i do not use globals-init=none, it seems having problem while widening global pointers in loop.

**Comment by arthaud** [comment]
Hi @wutianba,

Thanks for reporting this. The problem was that the widening was not applied on pointer sets, in the value domain. See the changes in 66d7137.

This is now fixed in master.
