### ISSUE TITLE
[regression] error: no member named 'getDestAlignment' in 'llvm::MemSetInst'; did you mean 'getAlignment'?

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#73]
rev. 4bc57ae fails:
```
/usr/ports/devel/ikos/work/ikos-2.1-46-g4bc57ae/frontend/llvm/src/import/function.cpp:551:47: error: no member named 'getDestAlignment' in 'llvm::MemSetInst'; did you mean 'getAlignment'?
                                      memset->getDestAlignment(),
                                              ^~~~~~~~~~~~~~~~
                                              getAlignment
/usr/local/include/llvm/IR/IntrinsicInst.h:483:14: note: 'getAlignment' declared here
    unsigned getAlignment() const {
             ^
/usr/ports/devel/ikos/work/ikos-2.1-46-g4bc57ae/frontend/llvm/src/import/function.cpp:1849:15: error: no member named 'FindDbgAddrUses' in namespace 'llvm'
        llvm::FindDbgAddrUses(alloca);
        ~~~~~~^
/usr/ports/devel/ikos/work/ikos-2.1-46-g4bc57ae/frontend/llvm/src/import/function.cpp:1854:36: error: no member named 'getExpression' in 'llvm::DbgInfoIntrinsic'
                       return dbg->getExpression()->getNumElements() == 0;
                              ~~~  ^
3 errors generated.
```

**Comment by arthaud** [comment]
Hi @yurivict,

I had a similar error when I migrated from LLVM 6 to LLVM 7.
LLVM 6 has `llvm::MemSetInst::getAlignment()`
LLVM 7 has `llvm::MemSetInst::getDestAlignment()`
See https://llvm.org/doxygen/classllvm_1_1MemIntrinsicBase.html#a6fa466783177c427903cc7d61ea79f57

Please make sure you are compiling with LLVM 7. We do not support older versions.

**Comment by arthaud** [comment]
I just noticed the path to llvm: `/usr/local/include/llvm`

It looks like `/usr/local/include` is before `/usr/local/llvm70/include` in the include search path, so when we `#include <llvm/XXX.h>` we find LLVM 6 instead of LLVM 7.

I'm not sure what is the best way to fix this.

**Comment by arthaud** [comment]
By curiosity, why do you have `/usr/local/include/llvm`?

I installed both `llvm60` and `llvm70` on FreeBSD 12.0, but I don't get anything under `/usr/local/include/llvm`. I get separate directories: `/usr/local/llvm60/include` and `/usr/local/llvm70/include`, which is perfect.

**Comment by yurivict** [comment]
> I installed both llvm60 and llvm70 on FreeBSD 12.0, but I don't get anything under /usr/local/include/llvm.

These were leftover files that I didn't realize were there.

**Comment by arthaud** [comment]
Is the issue fixed if you remove that directory?

**Comment by yurivict** [comment]
Stray files is what caused it.
