### ISSUE TITLE
Clang cannot output bc to a folder that does not exist in windows

### ISSUE THREAD

**Issue by wutianba** [NASA-SW-VnV/ikos#76]
Hi,
In my compuer with Win10, Clang(both downloaded from offical website or built with mingw32) cannot output bc to a folder that does not exist such as `c:/usrs/xxxx/appdata/local/temp/ikos-jteqix/1.bc`. So that ikos would not generate bc files to analyze.

**Comment by arthaud** [comment]
Hi @wutianba,

Could you please provide the output of `ikos -vvv loop.c`?
The directory should be created by python, see [analyzer.py#L499](https://github.com/NASA-SW-VnV/ikos/blob/8c7421b99221f234850a253b096aa6f7196f50dc/analyzer/python/ikos/analyzer.py#L496)

**Comment by wutianba** [comment]
Sorry, I made a mistake. My changes to libllvmmc and libllvmsupport have caused these problems.
