### ISSUE TITLE
Fails on a particular function: function @_ZL12formatUInt64m has more than one ehresume block

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#77]
Compiling this file https://github.com/yurivict/gas-simulator/blob/master/main.cpp fails:

```
$ ikos -DDBG_TRACK_PARTICLES=1 main.cpp
<...skipped...>
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-W2A5mo/main.pp.bc: error: function @_ZL12formatUInt64m has more than one ehresume block (use the -mergereturn pass?)
ikos: error: a run-time error occurred
```

**Comment by practicalswift** [comment]
@yurivict To facilitate reproducing would you mind adding the required headers to the repo so that it can be reproduced simply by cloning and running `ikos -DDBG_TRACK_PARTICLES=1 main.cpp`? :-)

**Comment by arthaud** [comment]
This should be fixed now.
