### ISSUE TITLE
Make failed with the following error

### ISSUE THREAD

**Issue by venkyjntu-git** [NASA-SW-VnV/ikos#8]
![screenshot from 2018-12-01 13 29 43](https://user-images.githubusercontent.com/16498572/49325745-849e3000-f56d-11e8-8521-ff0441f06982.png)

**Comment by venkyjntu-git** [comment]
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: /usr/bin/gcc-8
-- Check for working C compiler: /usr/bin/gcc-8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- All libraries and binaries will be installed in /home/venkatesh/Desktop/Vtools/ikos-master/install
-- Including core
-- All libraries and binaries will be installed in /home/venkatesh/Desktop/Vtools/ikos-master/install
-- Found Boost: /usr/local/include (found version "1.66.0")
-- Found the following Boost libraries:
--   unit_test_framework
-- Found GMP: /usr/include/x86_64-linux-gnu  
-- Could NOT find MPFR. Please provide -DMPFR_ROOT=/path/to/mpfr (missing: MPFR_INCLUDE_DIR MPFR_LIB MPFR_VERSION_OK) (Required is at least version "1.0.0")
-- Could NOT find PPL. Please provide -DPPL_ROOT=/path/to/ppl (missing: PPL_INCLUDE_DIR PPL_LIB PPL_C_LIB) 
-- Could NOT find APRON. Please provide -DAPRON_ROOT=/path/to/apron (missing: APRON_INCLUDE_DIR APRON_APRON_LIB APRON_BOX_LIB APRON_OCT_LIB APRON_POLKA_LIB APRON_PPL_LIB APRON_PKGRID_LIB MPFR_FOUND PPL_FOUND) 
-- Performing Test CXX_SUPPORTS_CXX14
-- Performing Test CXX_SUPPORTS_CXX14 - Success
-- Performing Test CXX_SUPPORTS_FVISIBILITY_INLINES_HIDDEN
-- Performing Test CXX_SUPPORTS_FVISIBILITY_INLINES_HIDDEN - Success
-- Performing Test CXX_SUPPORTS_WALL
-- Performing Test CXX_SUPPORTS_WALL - Success
-- Performing Test CXX_SUPPORTS_WEXTRA
-- Performing Test CXX_SUPPORTS_WEXTRA - Success
-- Performing Test CXX_SUPPORTS_WEVERYTHING
-- Performing Test CXX_SUPPORTS_WEVERYTHING - Failed
-- Performing Test CXX_SUPPORTS_WNO_SWITCH_ENUM
-- Performing Test CXX_SUPPORTS_WNO_SWITCH_ENUM - Success
-- Performing Test CXX_SUPPORTS_WNO_PADDED
-- Performing Test CXX_SUPPORTS_WNO_PADDED - Success
-- Performing Test CXX_SUPPORTS_WNO_CXX98_COMPAT
-- Performing Test CXX_SUPPORTS_WNO_CXX98_COMPAT - Success
-- Performing Test CXX_SUPPORTS_WNO_CXX98_COMPAT_PEDANTIC
-- Performing Test CXX_SUPPORTS_WNO_CXX98_COMPAT_PEDANTIC - Success
-- Performing Test CXX_SUPPORTS_WNO_C99_EXTENSIONS
-- Performing Test CXX_SUPPORTS_WNO_C99_EXTENSIONS - Success
-- Performing Test CXX_SUPPORTS_WNO_COVERED_SWITCH_DEFAULT
-- Performing Test CXX_SUPPORTS_WNO_COVERED_SWITCH_DEFAULT - Success
-- Performing Test CXX_SUPPORTS_WNO_EXIT_TIME_DESTRUCTORS
-- Performing Test CXX_SUPPORTS_WNO_EXIT_TIME_DESTRUCTORS - Success
-- Performing Test CXX_SUPPORTS_WNO_GLOBAL_CONSTRUCTORS
-- Performing Test CXX_SUPPORTS_WNO_GLOBAL_CONSTRUCTORS - Success
-- Performing Test CXX_SUPPORTS_WNO_WEAK_VTABLES
-- Performing Test CXX_SUPPORTS_WNO_WEAK_VTABLES - Success
-- Performing Test CXX_SUPPORTS_WNO_DISABLED_MACRO_EXPANSION
-- Performing Test CXX_SUPPORTS_WNO_DISABLED_MACRO_EXPANSION - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") found components:  doxygen dot 
-- Including ar
-- All libraries and binaries will be installed in /home/venkatesh/Desktop/Vtools/ikos-master/install
-- Found Boost: /usr/local/include (found version "1.66.0")
-- Including frontend/llvm
-- All libraries and binaries will be installed in /home/venkatesh/Desktop/Vtools/ikos-master/install
-- Found Boost: /usr/local/include (found version "1.66.0")
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found LLVM: /home/venkatesh/Downloads/LLVM4/build (found version "4.0.0") 
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Success
-- Building with -fPIC
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_CXX11
-- Performing Test CXX_SUPPORTS_CXX11 - Success
-- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS
-- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS - Success
-- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS
-- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test C_SUPPORTS_FDATA_SECTIONS
-- Performing Test C_SUPPORTS_FDATA_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS - Success
-- Including analyzer
-- All libraries and binaries will be installed in /home/venkatesh/Desktop/Vtools/ikos-master/install
-- Found Boost: /usr/local/include (found version "1.66.0")
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found SQLite3: /usr/include  
-- Could NOT find MPFR. Please provide -DMPFR_ROOT=/path/to/mpfr (missing: MPFR_INCLUDE_DIR MPFR_LIB MPFR_VERSION_OK) (Required is at least version "1.0.0")
-- Could NOT find PPL. Please provide -DPPL_ROOT=/path/to/ppl (missing: PPL_INCLUDE_DIR PPL_LIB PPL_C_LIB) 
-- Could NOT find APRON. Please provide -DAPRON_ROOT=/path/to/apron (missing: APRON_INCLUDE_DIR APRON_APRON_LIB APRON_BOX_LIB APRON_OCT_LIB APRON_POLKA_LIB APRON_PPL_LIB APRON_PKGRID_LIB MPFR_FOUND PPL_FOUND) 
-- Found PythonInterp: /home/venkatesh/anaconda3/bin/python (found version "3.7") 
-- Building with -fPIC
-- Found Clang: /home/venkatesh/Downloads/LLVM4/build/bin/clang (found version "4.0.0") 
-- Performing Test CXX_SUPPORTS_WNO_UNUSED_LOCAL_TYPEDEFS
-- Performing Test CXX_SUPPORTS_WNO_UNUSED_LOCAL_TYPEDEFS - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/venkatesh/Desktop/Vtools/ikos-master/build
Output of the cmake, please help me in installing

**Comment by didjcodt** [comment]
Hello,
Did you try installing following the instructions on https://github.com/NASA-SW-VnV/ikos/blob/master/doc/INSTALL_UBUNTU_18.04.md? 
Maybe it is related to llvm version (https://reviews.llvm.org/file/data/dne62cacltxzlnoomqfi/PHID-FILE-dovthcvxpumiw7lp6aw6/D31303.diff)?

**Comment by arthaud** [comment]
Hi @venkyjntu-git,

As @didjcodt said, it looks like IKOS is trying to compile with a newer version of LLVM (probably 6 ou 7), thus the compiler errors.

If you have installed LLVM using `apt-get` in the past, I guess IKOS probably picked it instead of your local `/home/venkatesh/Downloads/LLVM4/build` if it's in a system path, such as `/usr/include`. Please check this first.

You can try `make VERBOSE=1` to see the compiler flags. The order of the `-I` arguments are important.

**Comment by venkyjntu-git** [comment]
Thank you verymuch
Yes, It is true it is taking from /usr/include, solved
