### ISSUE TITLE
ikos-scan fails: error: unknown argument: '-faddrsig'

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#92]
ikos fails on a very simple C++ make project:
```
$ ikos-scan make 
ikos-scan-c++ -O2 -c tsne.cpp
error: unknown argument: '-faddrsig'
*** Error code 1
```

FreeBSD 11.2 amd64

```-faddrsig``` doesn't appear in the Makefile.

**Comment by arthaud** [comment]
ikos-scan parses the command line arguments provided to the compiler.
It received the flag `-faddrsig` and it doesn't understand it, hence the error.

> `-faddrsig` doesn't appear in the Makefile.

It might be in a Makefile in a subdirectory or in the `CFLAGS` environment variable.
It's not coming from ikos, see https://github.com/NASA-SW-VnV/ikos/search?q=addrsig

Anyway, I can easily fix this.

Is the project generating the error accessible somewhere? It would be better if I could try my fix directly on it.

**Comment by arthaud** [comment]
I cannot reproduce, so I believe this is because you have `-faddrsig` in the `CFLAGS` environment variable.

What is the output of `$ echo $CFLAGS`?

**Comment by yurivict** [comment]
Both CFLAGS and CXXFLAGS are empty.
This is also evidenced by the output:
```
$ gmake
c++  -c x.cpp
c++  x.o -o x
```

**Comment by yurivict** [comment]
When x.o is missing, the error is:
```
$ ikos-scan gmake
ikos-scan-c++  -c x.cpp
error: unknown argument: '-faddrsig'
gmake: *** [Makefile:5: x.o] Error 1
```

When x.o is present, it fails with the different error:
```
$ ikos-scan gmake
ikos-scan-c++  x.o -o x
llvm-link: Not enough positional command line arguments specified!
Must specify at least 1 positional argument: See: llvm-link -help
gmake: *** [Makefile:2: x] Error 1
```

**Comment by arthaud** [comment]
I just checked the code and `-faddrsig` should be handled properly by ikos-scan. I still don't understand where this `-faddrsig` flag comes from.

What is the output of `ikos-scan -vvv make`?

**Comment by yurivict** [comment]
```
$ ikos-scan -vvv
usage: ikos-scan [options] command
ikos-scan: error: too few arguments
```

**Comment by yurivict** [comment]
```
$ ikos-scan -vvv make
[.] Running make -e
ikos-scan-c++ -O2 -pipe -fno-omit-frame-pointer -c x.cpp
[.] Running clang++ -O2 -pipe -fno-omit-frame-pointer -c x.cpp
error: unknown argument: '-faddrsig'
*** Error code 1
```

**Comment by arthaud** [comment]
Do you get the same error if you run `clang++ -O2 -pipe -fno-omit-frame-pointer -c x.cpp` using clang 7?

**Comment by yurivict** [comment]
No.

**Comment by arthaud** [comment]
Are you sure you are using the same clang as IKOS? Use `ikos-config --clang` to get the path to clang.
Do you get an error if you run `clang -O2 -pipe -fno-omit-frame-pointer -c x.cpp` (using clang instead of clang++)?

I'm pretty sure the error is in clang, since IKOS does not event contain the string "unknown argument" (except in a comment).

**Comment by yurivict** [comment]
Yes:
```
$ ikos-config --clang
/usr/local/llvm70/bin/clang
[yuri@yv /tmp/bhtsne/x]$ /usr/local/llvm70/bin/clang++ -O2 -pipe -fno-omit-frame-pointer -c x.cpp 
[yuri@yv /tmp/bhtsne/x]$ 
```

**Comment by arthaud** [comment]
Please try `/usr/local/llvm70/bin/clang -O2 -pipe -fno-omit-frame-pointer -c x.cpp` (clang instead of clang++).

**Comment by yurivict** [comment]
No error with clang:
```
[yuri@yv /tmp/bhtsne/x]$ clang70 -O2 -pipe -fno-omit-frame-pointer -c x.cpp
[yuri@yv /tmp/bhtsne/x]$ 
```

**Comment by arthaud** [comment]
I will try to reproduce it in a FreeBSD virtual machine.

**Comment by yurivict** [comment]
In a VM, you can install ikos with ```pkg install ikos```.

**Comment by arthaud** [comment]
This is really weird. It might be a bug in clang.

The following code produces the error:
```python
import subprocess
p = subprocess.Popen(['clang++', '-O2', '-pipe', '-c', 'x.cpp'],
    executable='/usr/local/llvm70/bin/clang++')
p.wait()
```

But this works:
```python
import subprocess
p = subprocess.Popen(['/usr/local/llvm70/bin/clang++', '-O2', '-pipe', '-c', 'x.cpp'],
    executable='/usr/local/llvm70/bin/clang++')
p.wait()
```

This only happens on FreeBSD.

**Comment by arthaud** [comment]
It seems like it could be fixed easily by adding `/usr/local/llvm70/bin` in the `PATH` automatically in ikos-scan. But I would like to understand what is actually happening.

**Comment by arthaud** [comment]
I got it!

```python
#!/usr/bin/env python2.7
import subprocess
p = subprocess.Popen(['clang++', '-v', '-O2', '-pipe', '-c', 'x.cpp'],
    executable='/usr/local/llvm70/bin/clang++')
p.wait()
```

Produces:
```
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-portbld-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
 "/usr/bin/clang++" -cc1 -triple x86_64-portbld-freebsd12.0 -emit-obj -disable-free -main-file-name x.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -coverage-notes-file /root/issue-92/x.gcno -resource-dir /usr/lib/clang/7.0.1 -internal-isystem /usr/include/c++/v1 -O2 -fdeprecated-macro -fdebug-compilation-dir /root/issue-92 -ferror-limit 19 -fmessage-length 0 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o x.o -x c++ x.cpp -faddrsig
error: unknown argument: '-faddrsig'
```

Apparently, clang calls back itself, but it calls `/usr/bin/clang++` instead of `/usr/local/llvm70/bin/clang++`. I will fix this by adding `/usr/local/llvm70/bin` in the `PATH`.

**Comment by yurivict** [comment]
> Apparently, clang calls back itself, but it calls /usr/bin/clang++ instead of /usr/local/llvm70/bin/clang++

This seems like a bug in clang.
