### ISSUE TITLE
Feature request: Add an option to the print full report to the terminal

### ISSUE THREAD

**Issue by practicalswift** [NASA-SW-VnV/ikos#95]
Add an option to print the full report to the terminal regardless of size.

By default the report is written to the terminal only if it contains 15 entries or less.

Use case: When using `ikos` in batched mode I prefer having the output written to the terminal regardless of size.

**Comment by arthaud** [comment]
Hi @practicalswift,

This is already possible using `ikos --format=text`

See the output of `ikos -h`:
```
  -f , --format         Available report formats:
                          auto  - Generate a text report on the terminal, if possible (default)
                          text  - Generate a text report
                          json  - Generate a json report
                          csv   - Generate a csv report
                          web   - Generate a web report (ikos-view)
                          no    - Do not generate a report
```

This is also described in [analyzer/README.md](https://github.com/NASA-SW-VnV/ikos/tree/master/analyzer#format)

**Comment by practicalswift** [comment]
Ah! I knew about that the `-f text` option but I assumed it wrote to disk since the "on the terminal" text was not included.

What about clarifying by changing to:

```
  -f , --format         Available report formats:
                          auto  - Generate a text report to the terminal if less than 15 report entries (default)
                          text  - Generate a text report to the terminal regardless of report size
```

**Comment by arthaud** [comment]
The report is always written on the report file (option `--report-file`), which is the standard output by default. This is regardless of `--format`, so saying "to the terminal" is probably misleading. I meant something like "convenient for the terminal".  I'm trying to keep it small so that it fits in one line. We could be more precise in `analyzer/README.md` though.

**Comment by practicalswift** [comment]
@arthaud I understand. Thanks for clarifying!
